/**
 * Business tools: generate a page for every engine/biz-*.js and wire it in.
 *
 *   node build-biz.js          apply
 *   node build-biz.js --check  report what would change, write nothing
 *
 * A tool is a single engine file that publishes its metadata on
 * window.BIZ_TOOLS[slug] and mounts itself into [data-tool=slug] .tool-io.
 * This script reads the metadata by running the file in Node (the file
 * stops before touching the DOM), writes /business/<slug>/index.html in the
 * site's current shape, and adds the search-index, sitemap and hub entries.
 * Counts, breadcrumbs, outbound tags and the PWA manifest are the job of
 * the passes that already do them: run build-sections, build-crumbs,
 * build-outbound and build-pwa after this, in that order.
 *
 * Run it on a clean export, never on the working tree.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const crumbs = require('./build-crumbs.js');
const { trailFor } = require('./build/sections.js');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const SITE = 'https://www.1234tools.com';
const SECTION = 'business';
const SHELL_PAGE = 'business/currency-converter/index.html';

const changes = [];
function write(rel, content) {
  const abs = path.join(ROOT, rel);
  const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (existing === content) return false;
  changes.push((existing === null ? 'create ' : 'update ') + rel);
  if (!CHECK) { fs.mkdirSync(path.dirname(abs), { recursive: true }); fs.writeFileSync(abs, content); }
  return true;
}
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const icon = (id) => '<svg class="ico" aria-hidden="true" focusable="false"><use href="/assets/icons.svg#' + id + '"></use></svg>';

/** Every biz-*.js, with its metadata. */
function tools() {
  const out = [];
  for (const f of fs.readdirSync(path.join(ROOT, 'engine')).filter(n => /^biz-.*\.js$/.test(n)).sort()) {
    const w = { window: {} };
    new Function('window', 'document', fs.readFileSync(path.join(ROOT, 'engine', f), 'utf8'))(w.window, undefined);
    for (const [slug, spec] of Object.entries(w.window.BIZ_TOOLS || {})) out.push({ slug, spec, file: '/engine/' + f });
  }
  return out;
}

function shell() {
  const src = fs.readFileSync(path.join(ROOT, SHELL_PAGE), 'utf8');
  const headEnd = src.indexOf('</head>');
  const open = '<main id="main" class="content">';
  const mainStart = src.indexOf(open);
  const mainEnd = src.indexOf('</main>');
  if (headEnd < 0 || mainStart < 0 || mainEnd < 0) throw new Error('could not read the shell from ' + SHELL_PAGE);
  return { head: src.slice(0, headEnd), mid: src.slice(headEnd, mainStart + open.length), tail: src.slice(mainEnd) };
}

function headFor(parts, t) {
  const url = SITE + '/' + SECTION + '/' + t.slug + '/';
  const title = t.spec.title + ' — Free Online | 1234Tools';
  let h = parts.head
    .replace(/<title>[^<]*<\/title>/, '<title>' + esc(title) + '</title>')
    .replace(/<meta name="description" content="[^"]*">/, '<meta name="description" content="' + esc(t.spec.description) + '">')
    .replace(/<link rel="canonical" href="[^"]*">/, '<link rel="canonical" href="' + url + '">')
    .replace(/<meta property="og:title" content="[^"]*">/, '<meta property="og:title" content="' + esc(title) + '">')
    .replace(/<meta property="og:description" content="[^"]*">/, '<meta property="og:description" content="' + esc(t.spec.description) + '">')
    .replace(/<meta property="og:url" content="[^"]*">/, '<meta property="og:url" content="' + url + '">')
    .replace(/<meta name="twitter:title" content="[^"]*">/, '<meta name="twitter:title" content="' + esc(title) + '">')
    .replace(/<meta name="twitter:description" content="[^"]*">/, '<meta name="twitter:description" content="' + esc(t.spec.description) + '">')
    .replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>\n?/, '')
    /* the PWA block belongs to the shell's own tool; build-pwa.js writes ours */
    .replace(/<!-- PWA: generated by build-pwa\.js, do not edit -->[\s\S]*?<!-- \/PWA -->\n?/, '')
    /* the shell's engine scripts are its own; ours go in their place */
    .replace(/(<script src="\/engine\/[^"]*"[^>]*><\/script>\n?)+/, t.spec.scripts.map(s => '<script src="' + s + '" defer></script>\n').join(''));
  return h;
}

const markActive = (html) => html
  .replace(/ class="side-link is-active"/g, ' class="side-link"')
  .replace('<a class="side-link" href="/' + SECTION + '/">', '<a class="side-link is-active" href="/' + SECTION + '/">');

function page(t, parts, all) {
  const pathOnly = '/' + SECTION + '/' + t.slug + '/';
  const url = SITE + pathOnly;
  const trail = trailFor(pathOnly);
  const related = all.filter(x => x.slug !== t.slug).map(x => '<li><a href="/' + SECTION + '/' + x.slug + '/">' + esc(x.spec.title) + '</a></li>')
    .concat(['<li><a href="/india/gst-calculator/">GST Calculator (India)</a></li>', '<li><a href="/business/invoice-payment-terms/">Invoice Due Date &amp; Settlement Discount Calculator</a></li>',
      '<li><a href="/developer/csv-to-json/">CSV to JSON Converter</a></li>', '<li><a href="/pdf/invoice-pdf/">Invoice Generator (PDF)</a></li>']).join('');
  const body =
    crumbs.render(trail, t.spec.title) + '\n' +
    '<article class="tool" data-tool="' + t.slug + '">\n' +
    '  <p class="eyebrow">Business</p>\n' +
    '  <h1>' + icon(t.spec.glyph).replace('class="ico"', 'class="ico ico-title"') + esc(t.spec.title) + '</h1>\n' +
    '  <p class="lede">' + esc(t.spec.description) + '</p>\n' +
    '  <div class="tool-io"></div>\n' +
    '  <section class="panel"><h2>Privacy</h2><p class="privacy-line">Your file never leaves your device. It is read and converted by your own browser, so nothing is uploaded, queued or logged — which is what makes this safe for a client’s books.</p></section>\n' +
    '  <section class="panel"><h2>Tips</h2><ul class="tips">' + t.spec.tips.map(x => '<li>' + esc(x) + '</li>').join('') + '</ul></section>\n' +
    '  <section class="panel"><h2>Frequently asked questions</h2>' + t.spec.faq.map(f => '<details><summary>' + esc(f.q) + '</summary><p>' + esc(f.a) + '</p></details>').join('') + '</section>\n' +
    '  <section class="panel"><h2>Related tools</h2><ul class="related">' + related + '</ul></section>\n' +
    '</article>\n';
  const ld = '<script type="application/ld+json">' + JSON.stringify({
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'SoftwareApplication', name: t.spec.title, description: t.spec.description, url, applicationCategory: 'BusinessApplication', operatingSystem: 'Any', offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' } },
      crumbs.breadcrumbList(trail, t.spec.title, pathOnly),
      { '@type': 'FAQPage', mainEntity: t.spec.faq.map(f => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }
    ]
  }) + '</script>\n';
  let html = markActive(headFor(parts, t) + ld + parts.mid + '\n' + body + parts.tail);
  /* build-pwa.js owns the PWA block. A page that already has one keeps it,
     otherwise this and build-pwa.js rewrite each other on every run. */
  const existingPath = path.join(ROOT, SECTION, t.slug, 'index.html');
  if (fs.existsSync(existingPath)) {
    const pwa = /<!-- PWA: generated by build-pwa\.js, do not edit -->[\s\S]*?<!-- \/PWA -->\n?/.exec(fs.readFileSync(existingPath, 'utf8'));
    if (pwa) html = html.replace('<link rel="stylesheet" href="/assets/app.css">', pwa[0] + '<link rel="stylesheet" href="/assets/app.css">');
  }
  return html;
}

/* ---------- wiring ---------- */

function patchSearchIndex(list) {
  const rel = 'assets/search-index.js';
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const add = list.filter(t => src.indexOf('"' + SECTION + '/' + t.slug + '/"') < 0)
    .map(t => '["' + t.spec.title.replace(/"/g, '\\"') + '","' + SECTION + '/' + t.slug + '/","' + t.slug + '"]');
  if (!add.length) return 0;
  write(rel, src.replace(/\];\s*$/, ',' + add.join(',') + '];\n'));
  return add.length;
}

function patchSitemap(list) {
  const rel = 'sitemap-1.xml';
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const add = list.filter(t => src.indexOf('<loc>' + SITE + '/' + SECTION + '/' + t.slug + '/</loc>') < 0)
    .map(t => '<url><loc>' + SITE + '/' + SECTION + '/' + t.slug + '/</loc><changefreq>monthly</changefreq><priority>0.7</priority></url>');
  if (!add.length) return 0;
  write(rel, src.replace('</urlset>', add.join('\n') + '\n</urlset>'));
  return add.length;
}

/** A card at the top of the business hub's grid: newest first. */
function patchHub(list) {
  const rel = SECTION + '/index.html';
  let html = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const at = html.indexOf('<div class="grid">');
  if (at < 0) throw new Error('the business hub has no card grid');
  const cards = list.filter(t => html.indexOf('href="/' + SECTION + '/' + t.slug + '/"') < 0).map(t =>
    '<a class="card" href="/' + SECTION + '/' + t.slug + '/"><span class="card-icon">' + icon(t.spec.glyph) + '</span><strong>' + esc(t.spec.title) + '</strong><span class="card-desc">' + esc(t.spec.description) + '</span></a>').join('');
  if (!cards) return false;
  const cut = at + '<div class="grid">'.length;
  return write(rel, html.slice(0, cut) + cards + html.slice(cut));
}

/** Every page that prints the site total. Stubs and drafts are skipped. */
function patchTotal(oldTotal, newTotal) {
  if (oldTotal === newTotal) return 0;
  let n = 0;
  (function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      if (name === 'node_modules' || name === '.git' || name === 'build') continue;
      const abs = path.join(dir, name);
      if (fs.statSync(abs).isDirectory()) { walk(abs); continue; }
      if (!name.endsWith('.html')) continue;
      const before = fs.readFileSync(abs, 'utf8');
      if (/name="robots" content="noindex,follow"/.test(before) && /http-equiv="refresh"/.test(before)) continue;
      if (before.indexOf(oldTotal) < 0) continue;
      const after = before.split(oldTotal).join(newTotal);
      const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
      changes.push('update ' + rel);
      if (!CHECK) fs.writeFileSync(abs, after);
      n++;
    }
  })(ROOT);
  return n;
}

/** Glyphs the tools need, drawn here so the sprite has them. */
const GLYPHS = {
  'i-tally': '<symbol id="i-tally" viewBox="0 0 24 24">\n  <rect x="3" y="4" width="8.5" height="16" rx="1.5"/>\n  <path d="M5.5 8.5h3.5M5.5 12h3.5M5.5 15.5h3.5" class="thin"/>\n  <path d="M14 8.5h7M18.5 6l2.5 2.5-2.5 2.5" class="thin"/>\n  <path d="M21 15.5h-7M16.5 13l-2.5 2.5 2.5 2.5" class="thin"/>\n</symbol>'
};
function patchIcons(list) {
  const rel = 'assets/icons.svg';
  let svg = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  let added = 0;
  for (const t of list) {
    const g = t.spec.glyph;
    if (svg.indexOf('id="' + g + '"') >= 0) continue;
    if (!GLYPHS[g]) throw new Error('no glyph drawn for ' + g);
    svg = svg.replace('</svg>', GLYPHS[g] + '\n</svg>');
    added++;
  }
  if (added) write(rel, svg);
  return added;
}

function bumpServiceWorker() {
  const rel = 'sw.js';
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  return write(rel, src.replace(/var V = '1234tools-v(\d+)';/, (m, n) => "var V = '1234tools-v" + (Number(n) + 1) + "';"));
}

function main() {
  const list = tools();
  if (!list.length) { console.log('\nbuild-biz.js: no engine/biz-*.js found\n'); return; }
  const parts = shell();
  let built = 0, fresh = 0;
  for (const t of list) {
    const rel = SECTION + '/' + t.slug + '/index.html';
    if (!fs.existsSync(path.join(ROOT, rel))) fresh++;
    if (write(rel, page(t, parts, list))) built++;
  }
  const home = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
  const m = /<small>([\d,]+)\+ free tools<\/small>/.exec(home);
  if (!m) throw new Error('could not read the tool total from index.html');
  const oldTotal = m[1];
  const newTotal = fresh ? (Number(oldTotal.replace(/,/g, '')) + fresh).toLocaleString('en-GB') : oldTotal;

  const indexed = patchSearchIndex(list);
  const mapped = patchSitemap(list);
  const hub = patchHub(list);
  const glyphs = patchIcons(list);
  const totals = patchTotal(oldTotal, newTotal);
  const sw = changes.length ? bumpServiceWorker() : false;

  console.log('\nbuild-biz.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  tools               ' + list.map(t => t.slug).join(', '));
  console.log('  pages written       ' + built + ' (' + fresh + ' new)');
  console.log('  search index        ' + (indexed ? indexed + ' added' : 'unchanged'));
  console.log('  sitemap             ' + (mapped ? mapped + ' added' : 'unchanged'));
  console.log('  business hub        ' + (hub ? 'card added' : 'unchanged'));
  console.log('  icons               ' + (glyphs ? glyphs + ' glyph(s) added' : 'unchanged'));
  console.log('  site total          ' + oldTotal + ' → ' + newTotal + (totals ? ' on ' + totals + ' pages' : ''));
  console.log('  service worker      ' + (sw ? 'bumped' : 'unchanged'));
  console.log('\n  ' + changes.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

if (require.main === module) main();
module.exports = { tools };
