/**
 * Section hubs grouped by the job, not the alphabet.
 *
 *   node build-hubs.js            apply
 *   node build-hubs.js --check    report what would change, write nothing
 *   node build-hubs.js --verbose  list the files
 *
 * A hub used to be a heading and one grid of every card in the section.
 * Twenty cards in no order the reader can predict is a wall; the only way
 * through it was to already know the tool's name. This rewrites each hub's
 * grid as one marker block:
 *
 *   - a one-line "Start here" with the one or two tools most people come for
 *   - a short intro that says, in the words people type, what the section does
 *   - a finder box scoped to the section, mounted by engine/finder.js
 *   - the same cards under Make / Convert / Check / Calculate / Clean up, each
 *     with a one-line "what goes in → what comes out" and its price tags
 *   - three questions and answers, also written into the page's JSON-LD
 *
 * Everything inside <!-- HUBS --> … <!-- /HUBS --> is derived: the cards from
 * the ones already on the page (so a generator that adds a card to the first
 * grid still works — the card is regrouped on the next run), the words from
 * build/jobs.js and the tables below. Every link the old grid had is asserted
 * to be present afterwards; a missing one stops the build.
 *
 * The PDF hub already groups its cards by job, by hand, under its own
 * headings. It keeps them: only the cards are decorated and the block holds
 * the intro, the start line and the finder.
 *
 * apply(html, rel) is a pure function of the page, so a generator that
 * rebuilds its hub (build-ai.js, build-ai-image.js) can call it and write
 * exactly what this script would write. Run it after build-sidebar.js and
 * build-sections.js and before build-crumbs.js.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { SECTIONS, sectionOf } = require('./build/sections.js');
const jobs = require('./build/jobs.js');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const VERBOSE = process.argv.includes('--verbose');
const SITE = 'https://www.1234tools.com';

const OPEN = '<!-- HUBS: generated by build-hubs.js, do not edit -->';
const CLOSE = '<!-- /HUBS -->';
const BLOCK = /<!-- HUBS: generated by build-hubs\.js, do not edit -->[\s\S]*?<!-- \/HUBS -->/;

/* Hubs that group their cards by job already, by hand. Their grids stay. */
const GROUPED = new Set(['/pdf/']);

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const unesc = (s) => String(s)
  .replace(/&(?:amp|#0*38);/g, '&').replace(/&(?:lt|#0*60);/g, '<').replace(/&(?:gt|#0*62);/g, '>')
  .replace(/&(?:quot|#0*34);/g, '"').replace(/&(?:#0*39|apos|#x27);/g, '\'').replace(/&nbsp;/g, ' ');
const isStub = (html) => /name="robots" content="noindex,follow"/.test(html) && /http-equiv="refresh"/.test(html);

/* ------------------------------------------------------------------ */
/* what each hub says                                                 */
/* ------------------------------------------------------------------ */

/* One paragraph each, in the words people type. Honest about what exists:
   there is no "compress PDF" on this site, so the PDF intro does not say
   there is. */
const INTRO = {
  '/business/': 'Business calculators and spreadsheet tools that run in your browser: a UK take-home pay calculator, profit margin and break-even calculators, a VAT return from a spreadsheet, a monthly payroll run with payslips, bank reconciliation and Tally converters. Nothing you open leaves your device, because nothing is uploaded.',
  '/ai/': 'AI tools for the paperwork of a business: an invoice data extractor that turns a PDF into a table, a bank statement categoriser, a contract summariser, and writers for business emails, product listings, job descriptions and social media posts. These call a language model on a server, say so before you press the button, and give you ten calls a month free.',
  '/pdf/': 'Free PDF tools that run in your browser: merge PDF files into one, split a PDF, rotate, delete or reorder pages, add a watermark, page numbers or a signature, convert PDF to JPG or PNG, and make invoices, payslips and certificates as PDF. No upload, no file size limit and no watermark on the output.',
  '/education/': 'Calculators for students and schools: convert CGPA to percentage and SGPA to CGPA, work out a marks percentage and an attendance percentage, convert rank to percentile, and count the days to an exam. For staff there is a timetable generator, an exam seating plan and report cards from a marks sheet, all in the browser.',
  '/india/': 'Indian tax and savings calculators: a GST calculator with the CGST, SGST and IGST split, income tax under the new and old regime, HRA exemption, TDS, capital gains and advance tax, plus SIP, PPF, EPF, NPS, FD and EMI calculators. The rates follow the current financial year, and each page says which.',
  '/developer/': 'Developer tools in the browser: a JSON formatter and validator, a regex tester, Base64 and URL encoders, a JWT decoder, a cron expression parser, a Markdown to HTML converter, and generators for UUIDs, meta tags, robots.txt and favicons. Paste, convert, copy; nothing is sent to a server.',
  '/image/': 'Image tools that run in your browser: compress an image, convert PNG to JPG or WebP, resize images in bulk, crop, rotate, remove a background, blur a face, strip EXIF data, and turn images into a PDF. Your photos stay on your device from start to finish.',
  '/ai-image/': 'AI photo tools that run on your own device: remove or blur a background, cut a sticker, erase an object or a person, blur faces, swap the sky, upscale, add film grain, make a 3D parallax clip or a thumbnail, or put text behind the subject. Small models your browser downloads once; export PNG, GIF or MP4 with no upload, no account and no watermark.',
  '/ai-video/': 'AI video tools that run on your own device. Reel Maker turns a script into a 9:16 Reel with animated text, your screenshots or screen recording, voice, music and captions; Auto Captions transcribes speech with Whisper inside your browser and burns word-by-word captions into a video, with SRT and VTT alongside. Nothing leaves your device; no upload, no account, no watermark.',
  '/text/': 'Text tools in the browser: a word counter with reading time, a text compare tool that shows the differences, readability scores, text clean-up, number to words, Morse code and Caesar cipher translators, and a password generator. Paste text, get the answer; nothing is stored.',
  '/mathematics/': 'Maths calculators that show the working: a percentage calculator, a fraction calculator, a quadratic equation solver, a statistics calculator for mean, median and standard deviation, LCM and GCD, prime factorisation, a Roman numeral converter, a number base converter and a scientific calculator.',
  '/finance/': 'Finance calculators for everyday decisions: a compound interest calculator with regular contributions, a loan payment calculator that shows the total interest paid, and a VAT and sales tax calculator that works in both directions. Each one shows the formula it used.',
  '/time/': 'Date and time calculators: a date difference calculator, an age calculator, add or subtract days from a date, find the week number, count business days between two dates, convert between time zones, and run a countdown or a stopwatch. Leap years and daylight saving are handled for you.',
  '/health/': 'Health calculators that explain their formulas: a BMI calculator, BMR and daily calorie needs, body fat percentage, heart rate training zones, daily water intake, a pregnancy due date calculator and an ovulation calculator. Each is an estimate, with a note on what it can and cannot tell you.',
  '/qr/': 'QR code tools in the browser: a QR code generator for links, WiFi, contact cards and UPI payments with custom colours and a logo, a bulk QR code generator from a list or a CSV, and a QR code scanner that reads a code from your camera or a picture and shows where a link really goes.',
  '/utilities/': 'Everyday tools in one place: the Tool Finder that takes a job in plain words and points to the right tool, a tip calculator and bill splitter, a square footage calculator, a fuel cost and MPG converter, a GPA calculator, a cooking measurement converter, a shoe size converter, a random number generator and a dice roller.',
  '/engineering/': 'Electronics and engineering calculators that show the formula: an Ohm’s law calculator that takes any two of voltage, current and resistance and gives the third and the power, and a gauge to absolute pressure converter for psig, psia, barg and bara. The plain unit conversions for pressure, energy and power live in the Conversions section.',
  '/design/': 'Design calculators in the browser: an aspect ratio calculator that scales a width or height proportionally and simplifies ratios for images and video. The colour and gradient tools sit in the Developer section, and the image tools handle resizing and cropping.'
};

/* Three each. A hub that already carries its own questions keeps them and
   gets none of these. */
const FAQ = {
  '/business/': [
    { q: 'Do these business tools send my figures or spreadsheets anywhere?', a: 'No. Every tool on this page runs in your browser. A spreadsheet you open is read on your device and the results are written there too; close the tab and nothing remains with us.' },
    { q: 'Are the UK tax and VAT figures current?', a: 'Each tool says on its own page which tax year and rules it uses, and the statutory tools carry the date the guidance was checked. They compute the figures; they do not file anything, and HMRC’s guidance is the authority.' },
    { q: 'Can I use these for Indian payroll and GST as well?', a: 'Yes. The payroll run, the CTC structure, the GSTR-2B reconciler and the e-invoice JSON generator follow Indian rules, and the India section has the GST, income tax and TDS calculators.' }
  ],
  '/education/': [
    { q: 'Which CGPA formula do these use?', a: 'The one you choose. CBSE, VTU, GTU and a plain ten-point scale are built in, and you can type your own university’s multiplier. Each result says which rule it used.' },
    { q: 'Are student names or marks uploaded?', a: 'No. The timetable, seating plan and report card tools read your spreadsheet on your device and write the PDFs there. Nothing is sent to us.' },
    { q: 'Do you have past papers or courses?', a: 'Not here. The learning resources directory collects courses and practice sets; this section is the arithmetic.' }
  ],
  '/india/': [
    { q: 'Which financial year do the tax calculators use?', a: 'The current one, named on each page, with both regimes side by side where the choice matters. When the Budget changes a slab the page is updated and the date of the check is shown.' },
    { q: 'Is the GST split right for inter-state supplies?', a: 'Yes. Choose inter-state and the tax shows as IGST; within a state it is split equally into CGST and SGST.' },
    { q: 'Do these replace a chartered accountant?', a: 'No. They give you the figure and the working so you can check it. Filing, planning and anything unusual belong with a professional.' }
  ],
  '/developer/': [
    { q: 'Is it safe to paste a token or production data here?', a: 'The page does not send what you paste anywhere; the work is done by JavaScript in your browser and works with the network off. Even so, treat live secrets with care and rotate anything you suspect has been exposed.' },
    { q: 'Does the JSON formatter handle large files?', a: 'Yes, within your browser’s memory. Files of several megabytes format in a moment; the limit is the machine, not an upload cap.' },
    { q: 'Which regex flavour does the tester use?', a: 'JavaScript’s, as implemented by your browser, with the flags shown. Most patterns written for PCRE behave the same, and lookbehind and named groups work in current browsers.' }
  ],
  '/image/': [
    { q: 'Are my photos uploaded?', a: 'No. The browser opens the file, does the work with its own canvas and writes the result back to your device. Nothing is sent, which is why the tools work offline.' },
    { q: 'Does compressing lose quality?', a: 'JPEG and WebP compression is lossy and you choose the level with a live preview and a before-and-after size. PNG stays lossless. Converting a JPEG to PNG does not restore detail that was already lost.' },
    { q: 'Is there a watermark or a file limit?', a: 'Neither. The output is yours, and the only limit is your device’s memory.' }
  ],
  '/text/': [
    { q: 'Is what I paste kept anywhere?', a: 'No. The text lives in the page while it is open and is gone when you close it. Nothing is sent to a server.' },
    { q: 'How does the word counter count words?', a: 'Runs of characters separated by spaces or line breaks, the way most word processors count. Reading time uses a typical words-per-minute rate, which the page shows.' },
    { q: 'Which readability scores are included?', a: 'Flesch Reading Ease, Flesch-Kincaid grade, Gunning Fog and SMOG, each with a short note on what the number means.' }
  ],
  '/mathematics/': [
    { q: 'Do the calculators show the steps?', a: 'The quadratic solver and the fraction and percentage calculators show the formula they used and the values along the way, so an answer can be checked rather than copied.' },
    { q: 'Which standard deviation does the statistics calculator give?', a: 'Both. Sample and population standard deviation are shown side by side, with the variance for each.' },
    { q: 'Can I use these in an exam?', a: 'That depends on your exam board, not on us. They are for learning and checking; a board that bans calculators bans these too.' }
  ],
  '/finance/': [
    { q: 'How often is interest compounded in the compound interest calculator?', a: 'You choose how often, and the result shows the effective annual rate so different frequencies can be compared.' },
    { q: 'Does the loan calculator handle overpayments?', a: 'The loan payment calculator gives the standard repayment and the total interest. For a payment-by-payment table with overpayments, use the loan amortisation schedule in the Business section.' },
    { q: 'Which VAT rate does the calculator use?', a: 'Whatever you type. The UK standard rate is offered, and the result shows net, tax and gross whichever direction you worked in.' }
  ],
  '/time/': [
    { q: 'What does the date difference calculator count?', a: 'The full time between the two dates, broken into years, months and days, with the totals in whole units. Monday to Wednesday is two days; add one yourself if you want both ends counted.' },
    { q: 'Which holidays does the business days calculator exclude?', a: 'Weekends, plus any dates you list as holidays. Public holidays differ by country and by year, so none are assumed.' },
    { q: 'Which time zones are supported?', a: 'All the IANA zones your browser knows, with daylight saving applied on the right dates for each.' }
  ],
  '/health/': [
    { q: 'Are these medical advice?', a: 'No. They apply published formulas to the numbers you enter and say what the result means in general terms. Anything about your own health belongs with a clinician.' },
    { q: 'Which formula does the BMR calculator use?', a: 'Mifflin-St Jeor, the one most dietitians use today, with the activity multipliers shown so you can see how the daily figure is built.' },
    { q: 'Is anything I enter stored?', a: 'No. Height, weight and dates stay in the page while it is open, and nothing is sent anywhere.' }
  ],
  '/qr/': [
    { q: 'Do the QR codes expire?', a: 'No. A QR code made here is the data drawn as a picture; there is no account, no redirect through our server and nothing to stop working later.' },
    { q: 'Can I add a logo and still have the code scan?', a: 'Yes, within limits. Raise the error correction level when you add a logo, and use the built-in scan check, which decodes the finished code before you download it.' },
    { q: 'Is the scanner’s camera feed sent anywhere?', a: 'No. Frames are decoded in your browser and never leave the device. The camera stops when you leave the page.' }
  ],
  '/utilities/': [
    { q: 'What does the Tool Finder do?', a: 'You describe the job in plain words and it names the tool to use, from everything on the site. It runs on your device: the list of tools is searched by your browser and nothing you type is sent anywhere.' },
    { q: 'Are the random numbers really random?', a: 'They come from your browser’s cryptographic random source, which is suitable for draws and passwords. The dice roller uses the same source.' },
    { q: 'Why does cups to grams depend on the ingredient?', a: 'Because a cup is a volume and ingredients differ in density. The converter uses a weight per cup for each ingredient on its list, which is why flour and sugar give different grams.' }
  ],
  '/engineering/': [
    { q: 'Does the Ohm’s law calculator handle power?', a: 'Yes. Enter any two of voltage, current and resistance and it works out the third and the power in watts.' },
    { q: 'Is psi to bar the same as psig to barg?', a: 'The numbers are, as long as both are gauge or both are absolute. Changing between gauge and absolute adds or takes away the atmospheric pressure, which the gauge to absolute pressure converter does.' },
    { q: 'Where are the unit conversions for engineering?', a: 'In the Conversions section: pressure, energy, power, speed, temperature and the rest, each pair on its own page with the formula.' },
    { q: 'Which engineering tools are coming?', a: 'The order depends on what people ask for. The Tool Finder takes requests, and so does the contact page.' }
  ],
  '/design/': [
    { q: 'How do I resize an image to a ratio, not just calculate it?', a: 'Use the aspect ratio calculator to get the pixel sizes, then the Bulk Image Resizer or the Image Cropper in the Image section to apply them.' },
    { q: 'Where are the colour tools?', a: 'The Colour Converter and Contrast Checker and the CSS Gradient Generator are in the Developer section; the Colour Palette Extractor is with the image tools.' },
    { q: 'Will there be more design tools?', a: 'Yes, as people ask for them. The Tool Finder takes requests, and so does the contact page.' }
  ]
};

/* Three starter questions for the section's finder box. */
const STARTERS = {
  '/business/': ['take-home pay from a salary', 'VAT return from a spreadsheet', 'payslips for the month'],
  '/ai/': ['read an invoice into a spreadsheet', 'summarise a contract', 'write a payment reminder email'],
  '/pdf/': ['merge two PDFs', 'PDF to JPG', 'sign a PDF'],
  '/education/': ['CGPA to percentage', 'attendance percentage I need', 'seating plan for an exam'],
  '/india/': ['GST on 10,000', 'new vs old regime tax', 'EMI on a home loan'],
  '/developer/': ['format this JSON', 'test a regex', 'decode a JWT'],
  '/image/': ['compress a JPEG', 'PNG to WebP', 'remove a photo background'],
  '/ai-image/': ['remove a photo background', 'erase a person from a photo', 'text behind a person in a photo'],
  '/ai-video/': ['make a reel from text', 'captions for a video', 'add a voiceover to a reel'],
  '/text/': ['count the words in my essay', 'compare two texts', 'readability of this text'],
  '/mathematics/': ['what is 15% of 240', 'solve a quadratic equation', 'mean and standard deviation'],
  '/finance/': ['compound interest on savings', 'monthly payment on a loan', 'add VAT to a price'],
  '/time/': ['days between two dates', 'how old am I in days', 'add 90 days to a date'],
  '/health/': ['my BMI', 'calories I need a day', 'due date from last period'],
  '/qr/': ['QR code for my WiFi', 'scan a QR code', 'QR codes from a CSV'],
  '/utilities/': ['which tool do I need', 'split a bill with tip', 'cups to grams'],
  '/engineering/': ['ohm’s law', 'psig to psia', 'psi to bar'],
  '/design/': ['aspect ratio for 1920 wide', '16:9 at 1280 wide', 'convert a colour to HSL']
};

/* ------------------------------------------------------------------ */
/* the pieces                                                         */
/* ------------------------------------------------------------------ */

/* The callable's address, read from the same config the account pages use.
   While it says REPLACE_ME there is nothing to post to and the box carries
   an empty endpoint, which the finder treats as "no request form". */
function endpoint() {
  const src = fs.readFileSync(path.join(ROOT, 'assets/firebase-config.js'), 'utf8');
  const get = (k) => (new RegExp(k + ": '([^']+)'").exec(src) || [])[1] || '';
  const project = get('projectId'), region = get('region') || 'asia-south1';
  if (!project || /REPLACE_ME/.test(project)) return null;
  return 'https://' + region + '-' + project + '.cloudfunctions.net/submitToolRequest';
}

/** url -> how many tools the register holds under it. */
let _counts = null;
function counts() {
  if (_counts) return _counts;
  _counts = {};
  for (const t of jobs.register()) {
    for (const url of Object.keys(SECTIONS)) {
      if (url === '/' || SECTIONS[url].meta) continue;
      if (t.path.indexOf(url) === 0) _counts[url] = (_counts[url] || 0) + 1;
    }
  }
  return _counts;
}

/** A tool section with a hub this script owns: not meta, not a conversion family, holds tools. */
const isHub = (s) => !!s && !s.meta && s.url !== '/' && s.url.indexOf('/conversions/') !== 0 && (counts()[s.url] || 0) > 0;
const hubs = () => Object.values(SECTIONS).filter(isHub);

let _titles = null;
function titleOf(p) {
  if (!_titles) { _titles = {}; for (const t of jobs.register()) _titles[t.path] = t.title; }
  return _titles[jobs.normalise(p)] || p;
}

/** data-sec on <body>: set to the slug, or removed when slug is null. Idempotent. */
function bodySec(html, slug) {
  return html.replace(/<body\b([^>]*)>/, function (m, attrs) {
    const a = attrs.replace(/\s+data-sec="[^"]*"/g, '');
    return '<body' + a + (slug ? ' data-sec="' + esc(slug) + '"' : '') + '>';
  });
}

const CARD = /<a class="card(?: [^"]*)?" href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/g;
const GRID = /<div class="grid">([\s\S]*?)<\/div>/g;

/** The parts of a card that are kept: its link, its glyph and its title. */
function parseCard(href, inner) {
  const icon = /<span class="card-icon">([\s\S]*?)<\/span>/.exec(inner);
  const title = /<strong>([\s\S]*?)<\/strong>/.exec(inner);
  const desc = /<span class="card-desc">([\s\S]*?)<\/span>/.exec(inner);
  return { href, icon: icon ? icon[1] : '', title: title ? title[1] : esc(titleOf(href)), desc: desc ? desc[1] : '' };
}

/** The card, written the one way. `job` null keeps the card's own words. */
function renderCard(card, slug, job) {
  const j = job || jobs.jobOf(card.href) || { io: '', tags: ['Free', 'On your device'] };
  const desc = job ? esc(jobs.descOf(card.href)) : card.desc;
  const tags = j.tags;
  const io = j.io;
  const cls = 'tag tag-' + (tags[0] === 'Free' ? 'free' : 'freemium');
  return '<a class="card" href="' + card.href + '" data-sec="' + esc(slug) + '">' +
    '<span class="card-icon">' + card.icon + '</span>' +
    '<strong>' + card.title + '</strong>' +
    '<span class="card-desc">' + desc + '</span>' +
    '<span class="card-io">' + esc(io) + '</span>' +
    '<span class="card-tags">' + tags.map((t) => '<span class="' + cls + '">' + esc(t) + '</span>').join('') + '</span>' +
    '</a>';
}

function startLine(sec) {
  const list = (jobs.START[sec.url] || []).filter((p) => jobs.register().some((t) => t.path === p));
  if (!list.length) return '';
  return '<p class="hub-start"><strong>Start here:</strong> ' +
    list.map((p) => '<a href="' + p + '">' + esc(titleOf(p)) + '</a>').join(', ') + '.</p>\n';
}

function introBlock(sec) {
  return INTRO[sec.url] ? '<p class="hub-intro">' + esc(INTRO[sec.url]) + '</p>\n' : '';
}

function finderBox(sec, withScript) {
  const opts = { inline: true, section: sec.slug, starters: STARTERS[sec.url] || [] };
  return '<section class="finder-inline" aria-label="' + esc('Find a tool in ' + sec.name) + '"><div class="tool-io" data-endpoint="' + esc(endpoint() || '') + '"></div></section>\n' +
    (withScript ? '<script src="/engine/finder.js" defer></script>\n' : '') +
    '<script>document.addEventListener(\'DOMContentLoaded\',function(){var r=document.querySelector(\'.finder-inline\');if(window.ToolFinder&&r)ToolFinder.mount(r,' + JSON.stringify(opts).replace(/<\//g, '<\\/') + ');});</script>\n';
}

function groups(cards, sec) {
  const byVerb = {};
  for (const c of cards) {
    const job = jobs.jobOf(c.href);
    const verb = job ? job.verb : jobs.VERBS[0];
    (byVerb[verb] = byVerb[verb] || []).push(renderCard(c, sec.slug, job));
  }
  return jobs.VERBS.filter((v) => byVerb[v]).map((v) =>
    '<h2 class="hub-verb">' + esc(v) + '</h2>\n<div class="grid">' + byVerb[v].join('') + '</div>\n').join('');
}

function faqBlock(sec) {
  const list = FAQ[sec.url];
  if (!list) return '';
  return '<section class="panel hub-faq"><h2>Frequently asked questions</h2>' +
    list.map((f) => '<details><summary>' + esc(f.q) + '</summary><p>' + esc(f.a) + '</p></details>').join('') +
    '</section>\n';
}

/**
 * The FAQPage node, kept in step with the visible questions: written when
 * `want`, removed when not, and never written beside somebody else's.
 */
function patchFaqLd(html, sec, want) {
  const re = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/;
  const m = re.exec(html);
  if (!m) return html;
  let data;
  try { data = JSON.parse(m[1]); } catch (e) { return html; }
  if (!Array.isArray(data['@graph'])) {
    const context = data['@context'] || 'https://schema.org';
    const self = Object.assign({}, data);
    delete self['@context'];
    data = { '@context': context, '@graph': [self] };
  }
  const graph = data['@graph'];
  const id = SITE + sec.url + '#faq';
  const mine = (x) => x && x['@type'] === 'FAQPage' && x['@id'] === id;
  const theirs = graph.some((x) => x && x['@type'] === 'FAQPage' && !mine(x));
  const at = graph.findIndex(mine);
  if (!want || theirs || !FAQ[sec.url]) {
    if (at < 0) return html;
    graph.splice(at, 1);
  } else {
    const node = {
      '@type': 'FAQPage', '@id': id,
      mainEntity: FAQ[sec.url].map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } }))
    };
    if (at >= 0) graph[at] = node; else graph.push(node);
  }
  return html.replace(re, function () { return '<script type="application/ld+json">' + JSON.stringify(data) + '</script>'; });
}

/** The section's tool cards in a run of html, in order, without duplicates. */
function toolCards(html, sec) {
  const out = [], seen = new Set();
  let m;
  CARD.lastIndex = 0;
  while ((m = CARD.exec(html))) {
    const href = m[1];
    if (href.indexOf(sec.url) !== 0 || href === sec.url || seen.has(href)) continue;
    seen.add(href);
    out.push(parseCard(href, m[2]));
  }
  return out;
}

/* ------------------------------------------------------------------ */
/* a hub                                                              */
/* ------------------------------------------------------------------ */

function hubPage(html, sec, rel) {
  const mainAt = html.indexOf('<main');
  const mainEnd = html.indexOf('</main>');
  if (mainAt < 0 || mainEnd < 0) throw new Error('build-hubs.js: ' + rel + ' has no <main>');
  let main = html.slice(mainAt, mainEnd);
  const before = toolCards(main, sec).map((c) => c.href);

  const hasOwnFaq = /<h2>Frequently asked questions<\/h2>/i.test(main.replace(BLOCK, ''));
  const hasFinderScript = /<script src="\/engine\/finder\.js"/.test(main.replace(BLOCK, '')) || /<script src="\/engine\/finder\.js"/.test(html.slice(0, mainAt));

  if (GROUPED.has(sec.url)) {
    /* The grids stay. Each card is rewritten the one way; the block goes
       after the hub's lede and holds the intro, the start line and the
       finder. */
    main = main.replace(CARD, function (m, href, inner) {
      if (href.indexOf(sec.url) !== 0 || href === sec.url) return m;
      return renderCard(parseCard(href, inner), sec.slug, null);
    });
    const block = OPEN + '\n' + introBlock(sec) + startLine(sec) + finderBox(sec, !hasFinderScript) + CLOSE;
    if (BLOCK.test(main)) main = main.replace(BLOCK, function () { return block; });
    else {
      const lede = main.indexOf('<p class="lede">');
      const at = lede < 0 ? -1 : main.indexOf('</p>', lede);
      if (at < 0) throw new Error('build-hubs.js: ' + rel + ' has no lede to put the block after');
      main = main.slice(0, at + 4) + '\n' + block + main.slice(at + 4);
    }
  } else {
    /* Collect the cards from the block and from any grid that holds this
       section's cards — the original grid, or one a generator added a card
       to — then replace the first of them with the block. */
    const cards = [];
    const seen = new Set();
    const take = (run) => { for (const c of toolCards(run, sec)) if (!seen.has(c.href)) { seen.add(c.href); cards.push(c); } };
    let cut = -1;
    const blockAt = main.search(BLOCK);
    if (blockAt >= 0) { take(BLOCK.exec(main)[0]); main = main.replace(BLOCK, '\u0000'); cut = blockAt; }
    main = main.replace(GRID, function (m, inner, offset) {
      const own = toolCards(inner, sec);
      if (!own.length) return m;
      take(m);
      if (cut < 0 || offset < cut) cut = offset;
      return '\u0000';
    });
    if (cut < 0) throw new Error('build-hubs.js: ' + rel + ' has no card grid and no HUBS block');
    if (!cards.length) throw new Error('build-hubs.js: ' + rel + ' has a grid with none of its own tools in it');
    const block = OPEN + '\n' + introBlock(sec) + startLine(sec) + finderBox(sec, !hasFinderScript) +
      groups(cards, sec) + (hasOwnFaq ? '' : faqBlock(sec)) + CLOSE;
    /* the first placeholder becomes the block; any others (an emptied second
       grid) vanish with the newline that followed them */
    let first = true;
    main = main.replace(/\u0000\n?/g, function (m) {
      if (first) { first = false; return block + (m.endsWith('\n') ? '\n' : ''); }
      return '';
    });
  }

  const after = toolCards(main, sec).map((c) => c.href);
  const lost = before.filter((h) => after.indexOf(h) < 0);
  if (lost.length) throw new Error('build-hubs.js: ' + rel + ' would lose ' + lost.length + ' link(s): ' + lost.join(', '));

  let out = html.slice(0, mainAt) + main + html.slice(mainEnd);
  out = patchFaqLd(out, sec, !GROUPED.has(sec.url) && !hasOwnFaq);
  return bodySec(out, sec.slug);
}

/**
 * The one entry point. A hub gets the full treatment; a tool page under a
 * tool section gets data-sec on its body; a page outside the tool sections
 * loses any data-sec a shell lent it; a conversion page is left alone.
 */
function apply(html, rel) {
  const r = String(rel).replace(/\\/g, '/').replace(/^\/+/, '');
  const url = '/' + r.replace(/index\.html$/, '');
  if (url.indexOf('/conversions/') === 0) return html;
  if (isStub(html)) return html;
  const own = SECTIONS[url];
  if (own && isHub(own)) return hubPage(html, own, r);
  const sec = sectionOf(url);
  if (sec && isHub(sec)) return bodySec(html, sec.slug);
  return bodySec(html, null);
}

/* ------------------------------------------------------------------ */

function pages() {
  const out = [];
  (function walk(dir, depth) {
    for (const name of fs.readdirSync(dir)) {
      if (name === 'node_modules' || name === '.git' || name === 'build' || name === 'engine' || name === 'assets') continue;
      if (depth === 0 && name === 'conversions') continue;
      const abs = path.join(dir, name);
      if (fs.statSync(abs).isDirectory()) walk(abs, depth + 1);
      else if (name.endsWith('.html')) out.push(abs);
    }
  })(ROOT, 0);
  return out;
}

function main() {
  const list = hubs();
  const changes = [];
  let hubsDone = 0, tagged = 0, stripped = 0, scanned = 0;
  const pending = [];
  for (const abs of pages()) {
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    const before = fs.readFileSync(abs, 'utf8');
    if (isStub(before)) continue;
    scanned++;
    const after = apply(before, rel);
    if (after === before) continue;
    const url = '/' + rel.replace(/index\.html$/, '');
    if (SECTIONS[url] && isHub(SECTIONS[url])) hubsDone++;
    else if (/data-sec=/.test(after)) tagged++;
    else stripped++;
    changes.push(rel);
    pending.push([abs, after]);
  }
  if (!CHECK) {
    pending.forEach(([abs, html]) => fs.writeFileSync(abs, html));
    if (pending.length) {
      const sw = path.join(ROOT, 'sw.js');
      const src = fs.readFileSync(sw, 'utf8');
      const out = src.replace(/var V = '1234tools-v(\d+)';/, (m, n) => "var V = '1234tools-v" + (Number(n) + 1) + "';");
      if (out !== src) { fs.writeFileSync(sw, out); changes.push('sw.js'); }
    }
  }
  console.log('\nbuild-hubs.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  hubs                ' + list.length + ' (' + list.map((s) => s.slug).join(', ') + ')');
  console.log('  grouped by hand     ' + [...GROUPED].join(', ') + ' (cards decorated, grids kept)');
  console.log('  pages scanned       ' + scanned + ' (conversions left alone)');
  console.log('  hubs rewritten      ' + hubsDone);
  console.log('  tool pages tagged   ' + tagged);
  console.log('  stale tags removed  ' + stripped);
  if (VERBOSE) changes.slice(0, 60).forEach((f) => console.log('    ' + f));
  console.log('\n  ' + changes.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

if (require.main === module) main();

module.exports = { apply, bodySec, hubs, isHub, INTRO, FAQ, STARTERS, GROUPED, OPEN, CLOSE, BLOCK, endpoint };
