/**
 * The tool stories, published for the site.
 *
 *   node build-stories.js          write assets/stories.js
 *   node build-stories.js --check  report whether it would change, write nothing
 *
 * build/promo/stories/<section>.js holds, for every tool, the moment a person
 * recognises (pain), why the usual ways annoy (usual), what this tool does
 * about it (promise), three steps and the proof. The promotion desk's kits
 * are built from it; this script publishes the same words for the pages that
 * tell the same story on the site — the Reel Maker's "Promote a tool" mode
 * and the story strip on each tool page — so the site, the kits and the
 * Reels never say different things about one tool.
 *
 * Only the words are published, never the example spec (an internal note
 * for the capture engine). Every string is linted with the promotion desk's
 * own truth rules for the tool's pricing and section, and a single error
 * stops the build: a sentence the desk would refuse to post must not reach
 * a page either. Tools without a written story fall back to the desk's
 * generated story and are counted in the report.
 *
 * Output is deterministic (sorted keys, no dates), so a second run writes
 * nothing. Inert on require.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const OUT = 'assets/stories.js';

function finderTools() {
  const w = {};
  new Function('window', fs.readFileSync(path.join(ROOT, 'assets/finder-index.js'), 'utf8'))(w);
  return w.FINDER_INDEX.tools.map((r) => ({ title: r[0], path: '/' + String(r[1]).replace(/^\/+/, ''), section: String(r[1]).split('/')[0] }));
}

function build() {
  const S = require('./build/promo/stories/index.js');
  const { lint } = require('./build/promo/lint.js');
  const tools = finderTools().sort((a, b) => a.path.localeCompare(b.path));
  const out = {};
  const problems = [];
  let written = 0;
  for (const t of tools) {
    const s = S.storyFor(t.path);
    if (!s) { problems.push(t.path + ': no story and no fallback'); continue; }
    if (s.source === 'story') written++;
    const pricing = t.path.indexOf('/ai/') === 0 ? 'freemium' : 'free';
    const rec = {
      persona: s.persona || '', hook: s.hook || '', pain: s.pain || '',
      usual: (s.usual || []).slice(0, 3), promise: s.promise || '',
      steps: (s.steps || []).slice(0, 3), proof: (s.proof || []).slice(0, 3),
      howTo: s.howTo || '', cta: s.cta || '', written: s.source === 'story'
    };
    for (const text of [rec.persona, rec.hook, rec.pain, rec.promise, rec.howTo, rec.cta].concat(rec.usual, rec.steps, rec.proof)) {
      if (!text) continue;
      const r = lint(text, { pricing, section: t.section });
      if (!r.ok) problems.push(t.path + ': "' + text + '" — ' + r.errors.map((e) => e.msg).join('; '));
    }
    out[t.path] = rec;
  }
  return { out, problems, total: tools.length, written };
}

function main() {
  const { out, problems, total, written } = build();
  if (problems.length) {
    console.error('\nbuild-stories.js: ' + problems.length + ' problem(s)\n  ' + problems.slice(0, 30).join('\n  '));
    process.exit(1);
  }
  const body = '/* Generated by build-stories.js from build/promo/stories — do not edit. */\n' +
    'window.TOOL_STORIES=' + JSON.stringify(out) + ';\n';
  const abs = path.join(ROOT, OUT);
  const was = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  const changed = was !== body;
  if (changed && !CHECK) fs.writeFileSync(abs, body);
  console.log('\nbuild-stories.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  tools               ' + total + ' (' + written + ' written stories, ' + (total - written) + ' generated)');
  console.log('  size                ' + (Buffer.byteLength(body) / 1024).toFixed(1) + ' KB');
  console.log('\n  ' + (changed ? 1 : 0) + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

if (require.main === module) main();
module.exports = { build };
