/**
 * Show, don't tell: a real example and the story on every tool page.
 *
 *   node build-proof.js            apply
 *   node build-proof.js --check    report what would change, write nothing
 *   node build-proof.js --verbose  list the files
 *
 * A tool page used to be a title, a one-line lede, the tool and some text.
 * Two things were known about every tool and shown nowhere: what it actually
 * produces (build/promo/examples.js ran each one in headless Chrome and kept
 * the result; build-examples.js publishes it as assets/examples.js and
 * assets/img/examples/) and why anybody reaches for it (the stories the
 * promotion desk writes, linted against the site's truth rules and published
 * by build-stories.js as assets/stories.js). This puts both on the page.
 *
 * Every edit is marker-delimited and a pure function of the page and those
 * two files:
 *
 *   <!-- PROOF: generated by build-proof.js, do not edit --> … <!-- /PROOF -->
 *
 *   1. under the lede of every non-conversion tool page (article.tool), the
 *      story's proof pills — "Free", "No sign-up", "Runs in your browser" —
 *      true for the tool's pricing because the story linter says so;
 *   2. after the share row (or after .calc / .tool-io where there is none):
 *      - an Example panel: a calculator's real inputs and its primary and
 *        two secondary results as the page formatted them, with "Try these
 *        numbers" carrying the inputs in the #fragment render-core already
 *        reads; a text tool's input and output with "Try it" (#text=); an
 *        image, video or PDF tool's before and after, as a comparison slider
 *        (a range input moving a clip-path; side by side without JS), lazy
 *        WebP with its width and height set. A schematic tool (the AI
 *        business tools, whose runs cost money) gets no Example panel;
 *      - a "Why people use it" panel: the pain, the three usual ways (✗),
 *        the promise (✓), and the three steps only where the page has no
 *        "How it works" panel of its own;
 *   3. on the section hubs and the /for/ collections, a 16:9 thumbnail of
 *      the result at the top of each card whose tool has a picture. On a
 *      hub it sits inside the card's .card-icon, the one part of a card
 *      build-hubs.js keeps verbatim when it rewrites the card;
 *   4. on the home page, a "See it work" strip of eight before-and-after
 *      tiles, as the marker block <!-- SEEITWORK --> after AUDIENCES, which
 *      build-home.js then keeps in its ORDER.
 *
 * No structured data is added: Google retired HowTo rich results in 2023,
 * and a rating or review that nobody gave is never written.
 *
 * Redirect stubs, noindex pages, drafts, /learn/, /practice/, /account/ and
 * /pwa/ are left alone; their old blocks, if any, are removed. The walk, the
 * draft rule and the service-worker bump are build-share.js's, and like it
 * apply(html, rel) is lent to the generators, which call it at write time
 * as proof.apply(share.apply(...), rel).
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { SECTIONS } = require('./build/sections.js');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const VERBOSE = process.argv.includes('--verbose');
const SITE = 'https://www.1234tools.com';

const OPEN = '<!-- PROOF: generated by build-proof.js, do not edit -->';
const CLOSE = '<!-- /PROOF -->';
const BLOCK_RE = /\n[ \t]*<!-- PROOF: generated by build-proof\.js, do not edit -->[\s\S]*?<!-- \/PROOF -->/g;
const SEE_OPEN = '<!-- SEEITWORK: generated by build-proof.js, do not edit -->';
const SEE_CLOSE = '<!-- /SEEITWORK -->';
const SEE_RE = /<!-- SEEITWORK(?::[^>]*)? -->[\s\S]*?<!-- \/SEEITWORK -->/;
const THUMB_RE = /<img class="card-thumb"[^>]*>/g;
const CARD_RE = /(<a class="card(?: [^"]*)?" href="([^"]+)"[^>]*>)([\s\S]*?<\/a>)/g;
const CALC_RE = /<div class="calc">[\s\S]*?<div class="tool-results"[^>]*><\/div>\s*<\/div>/;
const IO_RE = /<div class="tool-io"(?: [^>]*)?><\/div>/;
const SHARE_END = '<!-- /SHARE -->';
const HOW_RE = /<h2[^>]*>\s*How (?:it works|to use)\b/i;
const CREDITS = '/assets/img/examples/CREDITS.txt';
const SCRIPT = '<script src="/assets/proof.js" defer></script>';

/* Not tool pages, whatever their markup says (build-share.js's list). */
const SKIP_PREFIX = ['practice/', 'account/', 'pwa/', 'learn/', 'conversions/'];
const SKIP_DIRS = new Set(['node_modules', '.git', 'build']);

/* The home strip: the most visual tools, each with what its own example
   shows. Names and figures come from the example; only the order and the
   short line of words are chosen here. */
const SEE = [
  { path: '/ai-image/background-remover/', line: () => 'Product photo → transparent PNG' },
  { path: '/ai-image/sky-replacement/', line: () => 'A clear sky → a sunset' },
  { path: '/ai-image/object-remover/', line: () => 'People removed from a street photo' },
  { path: '/ai-video/auto-captions/', line: () => 'Word-by-word captions from the clip’s own speech' },
  { path: '/image/image-compressor/', line: (ex) => statPair(ex, 'Original total', 'Result total', 'Change') },
  { path: '/pdf/merge-pdf/', line: (ex) => stat(ex, 'Files merged') + ' PDFs → one file · ' + stat(ex, 'Total pages') + ' pages' },
  { path: '/pdf/invoice-pdf/', line: (ex) => 'Total due ' + stat(ex, 'Total due') + ' · ' + stat(ex, 'Line items') + ' line items' },
  { path: '/india/gst-calculator/', calc: { lead: (by) => by('Invoice total').value + ' incl. ' + by('GST rate').value.replace(/\s+—.*$/, '') + ' GST', big: 'Taxable value', rows: ['CGST', 'SGST'] }, line: () => 'GST taken out of a total, split for the invoice' }
];

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const isStub = (html) => /name="robots" content="noindex/.test(html) && /http-equiv="refresh"/.test(html);
const isNoindex = (html) => /<meta name="robots" content="noindex/.test(html);

/* ---------- data ---------- */

let data = null;
function load(file, name) {
  const abs = path.join(ROOT, file);
  if (!fs.existsSync(abs)) return {};
  const w = {};
  new Function('window', fs.readFileSync(abs, 'utf8'))(w);
  return w[name] || {};
}
function D() {
  if (!data) data = { stories: load('assets/stories.js', 'TOOL_STORIES'), examples: load('assets/examples.js', 'TOOL_EXAMPLES') };
  return data;
}

function stat(ex, label) {
  const s = (ex.stats || []).find((x) => x[0] === label);
  if (!s) throw new Error('build-proof.js: the ' + ex.title + ' example has no "' + label + '" figure');
  return s[1];
}
function statPair(ex, a, b, c) {
  const ch = (ex.stats || []).find((x) => x[0] === c);
  const pct = ch ? /\(([^)]+)\)/.exec(ch[1]) : null;
  return stat(ex, a) + ' → ' + stat(ex, b) + (pct ? ' (' + pct[1] + ')' : '');
}

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
function longDate(iso) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso || '');
  return m ? Number(m[3]) + ' ' + MONTHS[Number(m[2]) - 1] + ' ' + m[1] : '';
}

/* ---------- where things go ---------- */

function urlOf(html, rel) {
  const m = /<link rel="canonical" href="([^"]+)"/.exec(html);
  if (m) return m[1].replace(SITE, '').replace(/[?#].*$/, '') || '/';
  return '/' + rel.replace(/index\.html$/, '').replace(/\.html$/, '/');
}

/** The offset just after the share row, or after the tool itself. */
function panelAnchor(html, articleAt) {
  const s = html.indexOf(SHARE_END, articleAt);
  const end = html.indexOf('</article>', articleAt);
  if (s > 0 && (end < 0 || s < end)) return s + SHARE_END.length;
  const rest = html.slice(articleAt);
  const m = CALC_RE.exec(rest) || IO_RE.exec(rest);
  return m ? articleAt + m.index + m[0].length : -1;
}

/* ---------- pieces ---------- */

const block = (body, indent) => (indent || '') + OPEN + '\n' + body + '\n' + (indent || '') + CLOSE;

function pills(story, hasExample) {
  const items = (story.proof || []).map((p) => '<li>' + esc(p) + '</li>');
  if (hasExample) items.push('<li class="proof-jump"><a href="#see-example">See a real example</a></li>');
  return '  <ul class="proof-pills" aria-label="At a glance">' + items.join('') + '</ul>';
}

const img = (src, size, alt, cls) => '<img' + (cls ? ' class="' + cls + '"' : '') + ' src="' + esc(src) + '" width="' + size[0] + '" height="' + size[1] +
  '" alt="' + esc(alt) + '" loading="lazy" decoding="async">';

function captured(ex) {
  const d = longDate(ex.captured);
  return d ? 'Captured from the live tool on <time datetime="' + esc(ex.captured) + '">' + esc(d) + '</time>.' : 'Captured from the live tool.';
}

function creditLine(ex) {
  if (ex.source === 'stock-photo') return 'Made with this tool from a free stock photo (CC0). <a href="' + CREDITS + '">Photo credits</a>';
  if (ex.source === 'stock-photo-voice') return 'Made with this tool from a free stock photo (CC0) and a synthesised voice. <a href="' + CREDITS + '">Photo credits</a>';
  if (ex.source === 'sample-pdf') return 'Made with this tool from a sample PDF the site’s own generators made.';
  return 'Made with this tool from the example details on this page.';
}

function fields(list, cls) {
  return '<dl class="' + cls + '">' + list.map((f) => '<div><dt>' + esc(f.label) + '</dt><dd>' + esc(f.value) + '</dd></div>').join('') + '</dl>';
}

function statList(stats) {
  if (!stats || !stats.length) return '';
  return '<ul class="proof-stats example-result">' + stats.slice(0, 4).map((s) => '<li><span>' + esc(s[0]) + '</span><strong>' + esc(s[1]) + '</strong></li>').join('') + '</ul>';
}

function head(title, badge, id) {
  return '<div class="proof-head"><h2 id="' + id + '">' + esc(title) + '</h2>' + (badge ? '<span class="proof-badge">' + esc(badge) + '</span>' : '') + '</div>';
}

function tryLink(href, kind, label) {
  return '<a class="btn-primary proof-try" href="' + esc(href) + '" data-proof-try="' + kind + '">' + esc(label) + '</a>';
}

function calcPanel(ex) {
  const primary = ex.results.find((r) => r.primary) || ex.results[0];
  const more = ex.results.filter((r) => r !== primary).slice(0, 2);
  const inputs = ex.inputs.slice(0, 8);
  return '<div class="proof-calc">' +
    '<div class="proof-in example-result-in"><span class="proof-k">You enter</span>' + fields(inputs, 'proof-fields') + '</div>' +
    '<span class="proof-arrow" aria-hidden="true"></span>' +
    '<div class="proof-out example-result"><span class="proof-k">You get</span>' +
    '<div class="proof-primary"><span class="proof-label">' + esc(primary.label) + '</span><span class="proof-value">' + esc(primary.value) + '</span></div>' +
    (more.length ? fields(more, 'proof-fields proof-more') : '') + '</div>' +
    '</div>' +
    (ex.message ? '<p class="proof-msg">' + esc(ex.message) + '</p>' : '') +
    '<p class="proof-foot">' + tryLink(ex.try || '#main', ex.try ? ex.form : 'tool', 'Try these numbers') +
    '<span class="proof-note">' + captured(ex) + '</span></p>';
}

function textPanel(ex) {
  return '<div class="proof-text">' +
    '<figure class="proof-pane example-result-in"><figcaption>' + esc(ex.inputLabel) + '</figcaption><pre>' + esc(ex.input) + '</pre></figure>' +
    '<span class="proof-arrow" aria-hidden="true"></span>' +
    '<figure class="proof-pane example-result"><figcaption>' + esc(ex.outputLabel) + '</figcaption><pre>' + esc(ex.output) + '</pre></figure>' +
    '</div>' + statList(ex.stats) +
    '<p class="proof-foot">' + tryLink(ex.try || '#main', ex.try ? 'text' : 'tool', 'Try it') +
    '<span class="proof-note">' + captured(ex) + '</span></p>';
}

function mediaPanel(ex, story) {
  const cap = ex.caption;
  let fig;
  const ar = (s) => (s[0] / s[1]).toFixed(3);
  if (ex.kind === 'beforeAfter' && ex.slider) {
    fig = '<figure class="proof-ba" data-proof-slider style="--pos:50%;--ar:' + ar(ex.afterSize) + '">' +
      '<div class="proof-stage">' +
      '<div class="proof-side proof-before">' + img(ex.before, ex.beforeSize, 'Before: ' + cap) + '<span class="proof-tag">Before</span></div>' +
      '<div class="proof-side proof-after">' + img(ex.after, ex.afterSize, 'After: ' + cap) + '<span class="proof-tag">After</span></div>' +
      '<input class="proof-range" type="range" min="0" max="100" step="1" value="50" aria-label="Drag to compare before and after" hidden>' +
      '<span class="proof-handle" aria-hidden="true"></span>' +
      '</div><figcaption>' + esc(cap) + '</figcaption></figure>';
  } else if (ex.kind === 'beforeAfter') {
    fig = '<figure class="proof-ba proof-pair">' +
      '<div class="proof-stage">' +
      '<div class="proof-side proof-before" style="--ar:' + ar(ex.beforeSize) + '">' + img(ex.before, ex.beforeSize, 'Before: ' + cap) + '<span class="proof-tag">Before</span></div>' +
      '<span class="proof-arrow" aria-hidden="true"></span>' +
      '<div class="proof-side proof-after" style="--ar:' + ar(ex.afterSize) + '">' + img(ex.after, ex.afterSize, 'After: ' + cap) + '<span class="proof-tag">After</span></div>' +
      '</div><figcaption>' + esc(cap) + '</figcaption></figure>';
  } else {
    const src = ex.page || ex.after;
    const size = ex.pageSize || ex.afterSize;
    const tall = size[1] > size[0] * 1.1;
    fig = '<div class="proof-doc' + (tall ? ' is-tall' : '') + '">' +
      '<figure class="proof-page">' + img(src, size, (ex.kind === 'document' ? 'Page 1 of the PDF it made: ' : 'What it made: ') + cap) + '</figure>' +
      '<div class="proof-facts">' + (ex.stats && ex.stats.length ? fields(ex.stats.map((s) => ({ label: s[0], value: s[1] })), 'proof-fields example-result') : '') +
      '<p class="proof-cap">' + esc(cap) + '</p></div></div>';
  }
  const stats = ex.kind === 'beforeAfter' ? statList(ex.stats) : '';
  return fig + stats +
    '<p class="proof-credit">' + creditLine(ex) + '</p>' +
    '<p class="proof-foot">' + tryLink('#main', 'tool', (story && story.cta) || 'Try it') +
    '<span class="proof-note">' + captured(ex) + '</span></p>';
}

function examplePanel(ex, story) {
  const badge = ex.kind === 'calc' || ex.kind === 'text' ? 'Real result from this tool' : 'Real output, made by this tool';
  let inner;
  if (ex.kind === 'calc') inner = calcPanel(ex);
  else if (ex.kind === 'text') inner = textPanel(ex);
  else inner = mediaPanel(ex, story);
  return '  <section class="panel proof proof-example proof-kind-' + ex.kind.toLowerCase() + '" id="see-example" aria-labelledby="proof-ex-h">' +
    head('Example', badge, 'proof-ex-h') + inner + '</section>\n  ' + SCRIPT;
}

function whyPanel(story, withSteps) {
  const usual = (story.usual || []).map((u) => '<li><span class="proof-x" aria-hidden="true">✗</span>' + esc(u) + '</li>').join('');
  const steps = withSteps && story.steps && story.steps.length
    ? '<ol class="proof-steps" aria-label="How it works">' + story.steps.map((s, i) => '<li><span class="proof-n" aria-hidden="true">' + (i + 1) + '</span>' + esc(s) + '</li>').join('') + '</ol>'
    : '';
  return '  <section class="panel proof proof-why" aria-labelledby="proof-why-h">' +
    head('Why people use it', story.persona ? 'For ' + story.persona : '', 'proof-why-h') +
    (story.pain ? '<p class="proof-pain">' + esc(story.pain) + '</p>' : '') +
    '<div class="proof-vs">' +
    (usual ? '<div class="proof-usual"><h3>The usual way</h3><ul>' + usual + '</ul></div>' : '') +
    (story.promise ? '<div class="proof-fix"><h3>With this tool</h3><p><span class="proof-check" aria-hidden="true">✓</span>' + esc(story.promise) + '</p></div>' : '') +
    '</div>' + steps +
    (story.cta ? '<p class="proof-cta"><a class="btn-ghost proof-go" href="#main" data-proof-try="tool">' + esc(story.cta) + ' ↑</a></p>' : '') +
    '</section>';
}

/* Persona text is written as a list of people ("Shop owners and
   accountants"); "For shop owners…" reads right, but a proper noun must
   keep its capital. */
function forWhom(p) {
  const first = p.split(/\s+/)[0];
  return /^[A-Z]{2,}|^[A-Z][a-z]+[A-Z]/.test(first) || /^(UK|US|India|Indian|British|HMRC|GST|VAT|CBSE)\b/.test(first) ? p : p.charAt(0).toLowerCase() + p.slice(1);
}

/* ---------- cards and the home strip ---------- */

function thumbFor(href) {
  const ex = D().examples[href];
  return ex && ex.thumb ? ex : null;
}

function addThumbs(html) {
  let n = 0;
  const out = html.replace(CARD_RE, function (m, open, href, rest) {
    if (/\bcard-lg\b/.test(open)) return m;
    const ex = thumbFor(href);
    if (!ex) return m;
    n++;
    const t = '<img class="card-thumb" src="' + esc(ex.thumb) + '" width="240" height="135" alt="" loading="lazy" decoding="async">';
    if (rest.indexOf('<span class="card-icon">') === 0) return open + '<span class="card-icon">' + t + rest.slice('<span class="card-icon">'.length);
    return open + t + rest;
  });
  return { html: out, n };
}

function seeTile(t) {
  const ex = D().examples[t.path];
  if (!ex) throw new Error('build-proof.js: the home strip wants ' + t.path + ', which has no published example');
  let pic;
  if (t.calc) {
    const by = (l) => (ex.results || []).find((r) => r.label === l) || (ex.inputs || []).find((r) => r.label === l);
    const big = by(t.calc.big);
    if (!big) throw new Error('build-proof.js: the ' + t.path + ' example has no "' + t.calc.big + '"');
    const need = (l) => { const f = by(l); if (!f) throw new Error('build-proof.js: the ' + t.path + ' example has no "' + l + '"'); return f; };
    const lead = t.calc.lead(need);
    pic = '<span class="see-pic see-readout example-result">' +
      '<span class="see-ro-in">' + esc(lead) + '</span>' +
      '<span class="see-ro-big">' + esc(big.value) + '</span><span class="see-ro-lab">' + esc(big.label) + '</span>' +
      '<span class="see-ro-rows">' + t.calc.rows.map(by).filter(Boolean).map((r) => '<span>' + esc(r.label) + ' <b>' + esc(r.value) + '</b></span>').join('') + '</span>' +
      '</span>';
  } else {
    if (!ex.thumb) throw new Error('build-proof.js: ' + t.path + ' has no picture for the home strip');
    const split = !!ex.thumbBefore;
    pic = '<span class="see-pic' + (split ? ' is-split' : '') + '">' +
      (split ? img(ex.thumbBefore, ex.thumbSize, '', 'see-before') : '') +
      img(ex.thumb, ex.thumbSize, ex.caption, 'see-after') +
      (split ? '<span class="see-tag see-tag-b">Before</span><span class="see-tag see-tag-a">After</span><span class="see-bar" aria-hidden="true"></span>' : '') +
      '</span>';
  }
  return '<a class="see-tile" href="' + esc(t.path) + '">' + pic +
    '<span class="see-txt"><strong>' + esc(ex.title) + '</strong><span class="see-line">' + esc(t.line(ex)) + '</span></span></a>';
}

function seeBlock() {
  return SEE_OPEN + '\n' +
    '<section class="home-see" aria-labelledby="see-head">\n' +
    '  <h2 class="section-title" id="see-head">See it work</h2>\n' +
    '  <p class="section-lede">Real results, made by the tools on this site from free stock photos and sample files. Not mock-ups.</p>\n' +
    '  <div class="see-grid">' + SEE.map(seeTile).join('') + '</div>\n' +
    '  <p class="see-credit">Photos: CC0 stock from Wikimedia Commons. <a href="' + CREDITS + '">Credits</a></p>\n' +
    '</section>\n' + SEE_CLOSE;
}

/* ---------- one page ---------- */

function isHubUrl(url) {
  const sec = SECTIONS[url];
  if (!sec || sec.meta) return false;
  try { return require('./build-hubs.js').isHub(sec); } catch (e) { return false; }
}

/**
 * Everything this script decides about one page.
 * Returns { html, skip, example, why, pills, thumbs, see }.
 */
function plan(src, rel) {
  rel = String(rel || '').replace(/\\/g, '/').replace(/^\/+/, '');
  if (typeof src !== 'string') return { html: src, skip: 'not html' };
  if (isStub(src)) return { html: src, skip: 'stub' };
  let html = src.replace(BLOCK_RE, '').replace(THUMB_RE, '');
  if (isNoindex(src)) return { html: html.replace(SEE_RE, ''), skip: 'noindex' };
  const r = { html };

  /* the home strip */
  if (rel === 'index.html') {
    const block = seeBlock();
    if (SEE_RE.test(html)) html = html.replace(SEE_RE, function () { return block; });
    else {
      const at = html.indexOf('<!-- /AUDIENCES -->');
      if (at < 0) return { html, skip: 'home without AUDIENCES' };
      const end = at + '<!-- /AUDIENCES -->'.length;
      html = html.slice(0, end) + '\n' + block + html.slice(end);
    }
    r.html = html; r.see = SEE.length;
    return r;
  }
  html = html.replace(SEE_RE, '');

  const url = urlOf(html, rel);

  /* cards: section hubs and collections */
  if (isHubUrl(url) || /^(hi\/)?for\//.test(rel)) {
    const t = addThumbs(html);
    html = t.html; r.thumbs = t.n;
  }

  /* tool pages */
  const articleAt = html.search(/<article class="tool[ "]/);
  if (articleAt < 0 || SKIP_PREFIX.some((p) => rel.indexOf(p) === 0)) { r.html = html; if (articleAt >= 0) r.skip = 'prefix'; return r; }
  const story = D().stories[url];
  const ex = D().examples[url];
  if (!story && !ex) { r.html = html; r.skip = 'no story'; return r; }

  /* the pills, under the lede */
  if (story && story.proof && story.proof.length) {
    const lede = html.indexOf('<p class="lede">', articleAt);
    const end = lede < 0 ? -1 : html.indexOf('</p>', lede);
    if (end > 0) {
      html = html.slice(0, end + 4) + '\n' + block(pills(story, !!ex), '  ') + html.slice(end + 4);
      r.pills = 1;
    }
  }

  /* the panels, after the share row */
  const at = panelAnchor(html, articleAt);
  if (at < 0) { r.html = html; r.skip = 'no anchor'; return r; }
  const howOwn = HOW_RE.test(html);
  const parts = [];
  if (ex) { parts.push(examplePanel(ex, story)); r.example = ex.kind; }
  if (story) {
    const s = Object.assign({}, story, { persona: story.persona ? forWhom(story.persona) : '' });
    parts.push(whyPanel(s, !howOwn)); r.why = 1; r.steps = !howOwn;
  }
  html = html.slice(0, at) + '\n' + block(parts.join('\n'), '  ') + html.slice(at);
  r.html = html;
  return r;
}

/** For generators: the page as this script would leave it. Pure. */
function apply(html, rel) {
  if (typeof html !== 'string') return html;
  return plan(html, rel).html;
}

/* ---------- the walk ---------- */

function pages() {
  const out = [];
  (function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      if (SKIP_DIRS.has(name)) continue;
      const abs = path.join(dir, name);
      if (fs.statSync(abs).isDirectory()) walk(abs);
      else if (name.endsWith('.html')) out.push(abs);
    }
  })(ROOT);
  return out;
}

/** Untracked HTML is somebody's unfinished work; it is not ours to rewrite. */
function unpublished() {
  const out = new Set();
  try {
    require('child_process')
      .execFileSync('git', ['ls-files', '--others', '--exclude-standard'],
        { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26, stdio: ['ignore', 'pipe', 'ignore'] })
      .split('\n').forEach(function (f) {
        const t = f.trim();
        if (t.endsWith('.html')) out.add(t);
      });
  } catch (e) { /* no git: treat everything as published */ }
  return out;
}

function bumpServiceWorker() {
  const abs = path.join(ROOT, 'sw.js');
  if (!fs.existsSync(abs)) return false;
  const src = fs.readFileSync(abs, 'utf8');
  const next = src.replace(/var V = '1234tools-v(\d+)';/, function (m, n) {
    return "var V = '1234tools-v" + (Number(n) + 1) + "';";
  });
  if (next === src) return false;
  if (!CHECK) fs.writeFileSync(abs, next);
  return true;
}

function main() {
  const drafts = unpublished();
  const files = [];
  const kinds = {}, skipped = {};
  let scanned = 0, why = 0, steps = 0, pillRows = 0, thumbs = 0, thumbPages = 0, see = 0;
  for (const abs of pages()) {
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (drafts.has(rel)) { (skipped.draft = skipped.draft || []).push(rel); continue; }
    if (rel.indexOf('conversions/') === 0) continue;
    scanned++;
    const before = fs.readFileSync(abs, 'utf8');
    const p = plan(before, rel);
    if (p.example) kinds[p.example] = (kinds[p.example] || 0) + 1;
    if (p.why) why++;
    if (p.steps) steps++;
    if (p.pills) pillRows++;
    if (p.thumbs) { thumbs += p.thumbs; thumbPages++; }
    if (p.see) see = p.see;
    if (p.skip && p.skip !== 'noindex' && p.skip !== 'stub') (skipped[p.skip] = skipped[p.skip] || []).push(rel);
    if (p.html !== before) {
      files.push(rel);
      if (!CHECK) fs.writeFileSync(abs, p.html);
    }
  }
  const sw = files.length ? bumpServiceWorker() : false;
  const total = Object.values(kinds).reduce((a, b) => a + b, 0);

  console.log('\nbuild-proof.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  pages scanned       ' + scanned + ' (conversions left alone)');
  console.log('  stories / examples  ' + Object.keys(D().stories).length + ' / ' + Object.keys(D().examples).length);
  console.log('  example panels      ' + total + ' (' + Object.entries(kinds).sort().map((k) => k[0] + ' ' + k[1]).join(', ') + ')');
  console.log('  why panels          ' + why + ' (' + steps + ' with steps, ' + (why - steps) + ' beside their own "How it works")');
  console.log('  proof pills         ' + pillRows);
  console.log('  card thumbnails     ' + thumbs + ' on ' + thumbPages + ' hub and collection pages');
  console.log('  home strip          ' + (see ? see + ' tiles' : 'not written'));
  Object.keys(skipped).sort().forEach(function (k) {
    const list = skipped[k];
    console.log('  skipped: ' + (k + ' ').padEnd(16) + String(list.length).padStart(5) +
      (k === 'no anchor' || k === 'no story' || k === 'home without AUDIENCES' || VERBOSE ? '   ' + list.slice(0, 8).join(', ') : ''));
  });
  console.log('  service worker      ' + (sw ? (CHECK ? 'would bump' : 'bumped') : 'unchanged'));
  if (VERBOSE) files.slice(0, 60).forEach(function (f) { console.log('    ' + f); });
  console.log('\n  ' + files.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

if (require.main === module) main();
module.exports = { apply, plan, OPEN, CLOSE, SEE_OPEN, SEE_CLOSE, SEE };
