/**
 * Depth: the reading part of every calculator page.
 *
 *   node build-depth.js            apply
 *   node build-depth.js --check    report what would change, write nothing
 *   node build-depth.js --verbose  list the files
 *
 * A calculator page has the tool, a real example and the story
 * (build-proof.js), a one-line formula, tips and a short FAQ. What it did
 * not have is the part somebody reads when they want to understand the
 * number rather than just get it: what the quantity is, how it is worked
 * out in words, a second worked example, what people use it for, the
 * mistakes people make and the questions they actually search. That text
 * lives in build/content/<section>.js, one object per page, and this puts
 * it on the page:
 *
 *   <!-- DEPTH: generated by build-depth.js, do not edit --> … <!-- /DEPTH -->
 *
 * after build-proof.js's "Why people use it" panel and before the page's
 * own Formula, Tips and FAQ panels. Its sections, each only when the
 * content has it: "What is …?", "How it is calculated", "Step by step"
 * (only where the page has no steps of its own), "Another worked example"
 * (with "Try these numbers", the same #fragment the Example panel uses),
 * "Common uses", "Mistakes to avoid", "More questions" and "Related
 * conversions and guides" (a link is written only when its page exists).
 *
 * The tools that work on files and text (/image/, /pdf/, /text/,
 * /developer/, /qr/) have the same block in a different shape: their entry
 * carries `howItWorks` ({ text, points }) in place of `formula`, rendered as
 * "How it works in your browser" (the method the page's own engine uses, as
 * a numbered list; `code spans` become <code>), and a worked example in
 * words with no "Try these numbers". On any page, a section whose heading
 * the page already gives one of its own panels is left out. The style for
 * the numbered list is kept in this file (D7-depth-files, after D7-depth in
 * app.css), so build/site/depth.css and the calculator pages are untouched.
 *
 * The "More questions" are also merged into the page's FAQPage in its
 * JSON-LD: appended to the existing FAQPage's mainEntity, each Question
 * with an @id ending "#depth-q<n>" so a re-run can take exactly its own
 * back out; a page without an FAQPage gets one (@id "#depth-faq"), never a
 * second.
 *
 * The worked example's container carries "example-result", like the
 * Example panel's, so the analytics MASK withholds its figures from a
 * replay. The stylesheet fragment build/site/depth.css is kept in assets/app.css
 * between its own markers, like every other D-block.
 *
 * The walk, the skip rules (stubs, noindex, untracked drafts, /learn/,
 * /practice/, /account/, /pwa/, /conversions/) and the service-worker bump
 * are build-proof.js's. apply(html, rel) is pure and lent to generators,
 * which call it as depth.apply(proof.apply(...), rel). Requiring this file
 * does nothing.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const VERBOSE = process.argv.includes('--verbose');
const SITE = 'https://www.1234tools.com';

const OPEN = '<!-- DEPTH: generated by build-depth.js, do not edit -->';
const CLOSE = '<!-- /DEPTH -->';
const BLOCK_RE = /\n[ \t]*<!-- DEPTH: generated by build-depth\.js, do not edit -->[\s\S]*?<!-- \/DEPTH -->/g;
const PROOF_END = '<!-- /PROOF -->';
const SHARE_END = '<!-- /SHARE -->';
const CALC_RE = /<div class="calc">[\s\S]*?<div class="tool-results"[^>]*><\/div>\s*<\/div>/;
const IO_RE = /<div class="tool-io"(?: [^>]*)?><\/div>/;
const PANEL_RE = /<section class="panel(?: [^"]*)?"/g;
const LD_RE = /<script type="application\/ld\+json">([\s\S]*?)<\/script>/;
const STEPS_RE = /class="proof-steps"|<h2[^>]*>\s*How (?:it works|to use)\b/i;
const CSS_OPEN = '/* ==== D7-depth ==== */';
const CSS_CLOSE = '/* ==== /D7-depth ==== */';
const CSS_AFTER = '/* ==== /D5-proof ==== */';
const Q_MARK = '#depth-q';
const FAQ_MARK = '#depth-faq';

const SKIP_PREFIX = ['practice/', 'account/', 'pwa/', 'learn/', 'conversions/'];
const SKIP_DIRS = new Set(['node_modules', '.git', 'build']);

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const isStub = (html) => /name="robots" content="noindex/.test(html) && /http-equiv="refresh"/.test(html);
const isNoindex = (html) => /<meta name="robots" content="noindex/.test(html);

/* ---------- the content ---------- */

/* `checks` is never rendered: it lists figures quoted outside the worked
   example, with the inputs that produce them, for build/content/_check.js.
   `runs` is never rendered either: on a file or text tool (an entry with
   `howItWorks` in place of `formula`) it records each run of the tool that
   a quoted figure came from, with its parameters, so it can be re-run. */
const KEYS = new Set(['term', 'whatTitle', 'whatIs', 'formula', 'howItWorks', 'howTo', 'worked', 'uses', 'mistakes', 'faq', 'related', 'checks', 'runs']);

function validate(url, d, file) {
  const where = 'build-depth.js: ' + file + ' ' + url;
  if (!/^\/[a-z0-9-]+\/[a-z0-9-]+\/$/.test(url)) throw new Error(where + ': a page path is /section/slug/');
  for (const k of Object.keys(d)) if (!KEYS.has(k)) throw new Error(where + ': unknown field "' + k + '"');
  const prose = (x) => (typeof x === 'string' && x) || (Array.isArray(x) && x.length && x.every((p) => typeof p === 'string' && p));
  if (!prose(d.whatIs)) throw new Error(where + ': whatIs is required (a string, or a list of paragraphs)');
  if (!d.term && !d.whatTitle) throw new Error(where + ': term (or whatTitle) is required');
  if (d.formula && (typeof d.formula.text !== 'string' || !d.formula.expr)) throw new Error(where + ': formula needs text and expr');
  if (d.howItWorks) {
    const h = d.howItWorks;
    if (d.formula) throw new Error(where + ': formula or howItWorks, not both');
    if (!prose(h.text) || !Array.isArray(h.points) || !h.points.length || !h.points.every((p) => typeof p === 'string' && p)) throw new Error(where + ': howItWorks needs text and a list of points');
  }
  if (d.runs !== undefined && !Array.isArray(d.runs)) throw new Error(where + ': runs is a list');
  if (d.worked && !prose(d.worked.text)) throw new Error(where + ': worked needs text');
  for (const k of ['uses', 'mistakes', 'faq', 'howTo']) if (d[k] !== undefined && !Array.isArray(d[k])) throw new Error(where + ': ' + k + ' is a list');
  (d.faq || []).forEach((f) => { if (!f || !f.q || !f.a) throw new Error(where + ': every faq entry has q and a'); });
  (d.uses || []).forEach((u) => { if (!Array.isArray(u) || u.length !== 2) throw new Error(where + ': every use is [title, sentence]'); });
}

let content = null;
function C() {
  if (content) return content;
  content = {};
  const dir = path.join(ROOT, 'build', 'content');
  if (!fs.existsSync(dir)) return content;
  for (const name of fs.readdirSync(dir).sort()) {
    if (!/^[a-z0-9-]+\.js$/.test(name)) continue;          /* _engine.js and friends are helpers */
    const map = require(path.join(dir, name));
    for (const url of Object.keys(map)) {
      if (content[url]) throw new Error('build-depth.js: ' + url + ' is in two content files');
      validate(url, map[url], name);
      content[url] = map[url];
    }
  }
  return content;
}

/* ---------- links: only to pages that exist ---------- */

const titles = new Map();
function pageTitle(href) {
  if (titles.has(href)) return titles.get(href);
  let t = null;
  if (/^\/[a-z0-9/-]+\/$/.test(href)) {
    const abs = path.join(ROOT, href.replace(/^\/+/, ''), 'index.html');
    if (fs.existsSync(abs)) {
      const html = fs.readFileSync(abs, 'utf8');
      if (!isStub(html) && !isNoindex(html)) {
        const h = /<h1[^>]*>([\s\S]*?)<\/h1>/.exec(html);
        const raw = h ? h[1] : ((/<title>([^<]*)/.exec(html) || [])[1] || '').replace(/\s*\|\s*1234Tools\s*$/, '');
        t = raw.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&#39;|&rsquo;/g, '’').replace(/\s+/g, ' ').trim() || null;
      }
    }
  }
  titles.set(href, t);
  return t;
}

/* ---------- pieces ---------- */

function urlOf(html, rel) {
  const m = /<link rel="canonical" href="([^"]+)"/.exec(html);
  if (m) return m[1].replace(SITE, '').replace(/[?#].*$/, '') || '/';
  return '/' + rel.replace(/index\.html$/, '').replace(/\.html$/, '/');
}

const para = (t) => (Array.isArray(t) ? t : [t]).map((p) => '<p>' + esc(p) + '</p>').join('');

function sec(id, title, body, cls) {
  return '<section class="depth-sec' + (cls ? ' ' + cls : '') + '" aria-labelledby="' + id + '"><h2 id="' + id + '">' + esc(title) + '</h2>' + body + '</section>';
}

function tryHref(inputs) {
  const q = new URLSearchParams();
  Object.keys(inputs).forEach((k) => q.set(k, String(inputs[k])));
  return '#' + q.toString();
}

/* `code spans` in a howItWorks text or point become <code>: the method is
   often a call (canvas.toBlob, JSON.parse) best read as code */
const inline = (s) => esc(s).replace(/`([^`]+)`/g, '<code>$1</code>');
const headingKey = (s) => String(s).toLowerCase().replace(/&amp;/g, '&').replace(/<[^>]+>/g, '').replace(/[^a-z0-9]+/g, ' ').trim();

function render(d, has) {
  const out = [];
  /* a section whose heading the page already uses for a panel of its own is
     left out: the page has that topic covered (the opening "What is" stays,
     it names the block) */
  const own = has.own || new Set();
  const push = (html) => { if (!own.has(headingKey(/<h2 [^>]*>(?:<span>)?([^<]*)</.exec(html)[1]))) out.push(html); };
  const what = d.whatTitle || ('What is ' + d.term + '?');
  out.push(sec('depth-what-h', what, para(d.whatIs), 'depth-what'));

  if (d.howItWorks) {
    const h = d.howItWorks;
    const text = (Array.isArray(h.text) ? h.text : [h.text]).map((p) => '<p>' + inline(p) + '</p>').join('');
    /* the heading's text sits in a <span>: build-proof.js reads an <h2> that
       opens "How it works" as the page's own steps panel and would then drop
       the three steps from its "Why people use it" panel */
    push(sec('depth-works-h', 'How it works in your browser', text + '<ol class="depth-points">' + h.points.map((p) => '<li>' + inline(p) + '</li>').join('') + '</ol>', 'depth-works')
      .replace('<h2 id="depth-works-h">How it works in your browser</h2>', '<h2 id="depth-works-h"><span>How it works in your browser</span></h2>'));
  }

  if (d.formula) {
    const f = d.formula;
    const exprs = (Array.isArray(f.expr) ? f.expr : [f.expr]).map((e) => '<code>' + esc(e) + '</code>').join('');
    const vars = (f.vars || []).length
      ? '<dl class="depth-vars">' + f.vars.map((v) => '<div><dt><code>' + esc(v[0]) + '</code></dt><dd>' + esc(v[1]) + '</dd></div>').join('') + '</dl>'
      : '';
    push(sec('depth-calc-h', 'How it is calculated', para(f.text) + '<div class="depth-formula" role="figure" aria-label="Formula">' + exprs + '</div>' + vars, 'depth-calc'));
  }

  if (d.howTo && d.howTo.length && !has.steps) {
    /* not "How to use …": build-proof.js reads that heading as the page's own steps */
    push(sec('depth-how-h', 'Step by step','<ol class="depth-steps">' + d.howTo.map((s) => '<li>' + esc(s) + '</li>').join('') + '</ol>', 'depth-how'));
  }

  if (d.worked) {
    const w = d.worked;
    const go = w.inputs && has.tool
      ? '<p class="depth-try"><a class="btn-ghost" href="' + esc(tryHref(w.inputs)) + '" data-proof-try="' + esc(has.tool) + '">Try these numbers ↑</a></p>'
      : '';
    push(sec('depth-worked-h', w.title || 'Another worked example', '<div class="depth-worked example-result">' + para(w.text) + '</div>' + go, 'depth-ex'));
  }

  if (d.uses && d.uses.length) {
    push(sec('depth-uses-h', 'Common uses', '<ul class="depth-uses">' + d.uses.map((u) => '<li><strong>' + esc(u[0]) + '</strong> ' + esc(u[1]) + '</li>').join('') + '</ul>', 'depth-use'));
  }

  if (d.mistakes && d.mistakes.length) {
    push(sec('depth-mistakes-h', 'Mistakes to avoid', '<ul class="depth-mistakes">' + d.mistakes.map((m) => '<li>' + esc(m) + '</li>').join('') + '</ul>', 'depth-mis'));
  }

  if (d.faq && d.faq.length) {
    push(sec('depth-faq-h', 'More questions', d.faq.map((f) => '<details><summary>' + esc(f.q) + '</summary><p>' + esc(f.a) + '</p></details>').join(''), 'depth-faq'));
  }

  const links = [];
  const r = d.related || {};
  (r.conversions || []).concat(r.guides || []).forEach((href) => {
    const t = pageTitle(href);
    if (t && !links.some((l) => l[0] === href)) links.push([href, t, (r.guides || []).includes(href) ? 'guide' : 'conversion']);
  });
  if (links.length) {
    const hasConv = links.some((l) => l[2] === 'conversion');
    const hasGuide = links.some((l) => l[2] === 'guide');
    const title = hasConv && hasGuide ? 'Related conversions and guides' : hasConv ? 'Related conversions' : 'Related guides';
    push(sec('depth-rel-h', title, '<ul class="related depth-related">' + links.map((l) =>
      '<li><a href="' + esc(l[0]) + '">' + esc(l[1]) + '</a><span class="depth-kind">' + l[2] + '</span></li>').join('') + '</ul>', 'depth-rel'));
  }

  return '<section class="panel depth" id="learn-more" aria-labelledby="depth-what-h">' + out.join('') + '</section>';
}

/* ---------- the FAQPage ---------- */

function patchLd(html, url, faq) {
  const m = LD_RE.exec(html);
  if (!m) return html;
  let data;
  try { data = JSON.parse(m[1]); } catch (e) { return html; }
  const mineQ = (q) => q && typeof q['@id'] === 'string' && q['@id'].indexOf(Q_MARK) > 0;
  const mineF = (x) => x && x['@type'] === 'FAQPage' && typeof x['@id'] === 'string' && x['@id'].slice(-FAQ_MARK.length) === FAQ_MARK;
  const wasGraph = Array.isArray(data['@graph']);
  let graph = wasGraph ? data['@graph'] : [data];

  /* take back what an earlier run added */
  let touched = false;
  graph.forEach((x) => {
    if (x && x['@type'] === 'FAQPage' && Array.isArray(x.mainEntity) && x.mainEntity.some(mineQ)) {
      x.mainEntity = x.mainEntity.filter((q) => !mineQ(q));
      touched = true;
    }
  });
  if (graph.some(mineF)) { graph = graph.filter((x) => !mineF(x)); touched = true; }

  if (faq && faq.length) {
    const qs = faq.map((f, i) => ({ '@type': 'Question', '@id': SITE + url + Q_MARK + (i + 1), name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } }));
    const page = graph.find((x) => x && x['@type'] === 'FAQPage');
    if (page) page.mainEntity = (Array.isArray(page.mainEntity) ? page.mainEntity : page.mainEntity ? [page.mainEntity] : []).concat(qs);
    else graph.push({ '@type': 'FAQPage', '@id': SITE + url + FAQ_MARK, mainEntity: qs });
    touched = true;
  }
  if (!touched) return html;

  let next;
  if (wasGraph) { data['@graph'] = graph; next = data; }
  else if (graph.length === 1) next = graph[0];
  else {
    const context = data['@context'] || 'https://schema.org';
    next = { '@context': context, '@graph': graph.map((x) => { const y = Object.assign({}, x); delete y['@context']; return y; }) };
  }
  return html.replace(LD_RE, function () { return '<script type="application/ld+json">' + JSON.stringify(next) + '</script>'; });
}

/* ---------- where it goes ---------- */

/** After the last PROOF block in the article, or after the share row or the tool. */
function afterTool(html, articleAt, end) {
  const p = html.lastIndexOf(PROOF_END, end);
  if (p > articleAt) return p + PROOF_END.length;
  const s = html.indexOf(SHARE_END, articleAt);
  if (s > 0 && s < end) return s + SHARE_END.length;
  const rest = html.slice(articleAt, end);
  const m = CALC_RE.exec(rest) || IO_RE.exec(rest);
  return m ? articleAt + m.index + m[0].length : -1;
}

/**
 * Before the first of the page's own panels (Formula, Tips, FAQ …) after
 * the tool, at the start of its line, so that the strip leaves the page
 * byte for byte as it was; otherwise straight after the proof panels.
 */
function insertAt(html, from, end) {
  PANEL_RE.lastIndex = from;
  let m;
  while ((m = PANEL_RE.exec(html)) && m.index < end) {
    if (/\bproof\b/.test(m[0])) continue;
    const nl = html.lastIndexOf('\n', m.index - 1);
    const lead = html.slice(nl + 1, m.index);
    if (nl > from && /^[ \t]*$/.test(lead)) return { at: nl, indent: lead };
    break;
  }
  return { at: from, indent: '  ' };
}

/** The headings of the page's own panels in the article (not build-proof.js's). */
function ownHeadings(article) {
  const own = new Set();
  const re = /<section class="panel(?: ([^"]*))?"[^>]*>\s*<h2[^>]*>([\s\S]*?)<\/h2>/g;
  let m;
  while ((m = re.exec(article))) if (!/\b(proof|depth)\b/.test(m[1] || '')) own.add(headingKey(m[2]));
  return own;
}

/* ---------- one page ---------- */

function plan(src, rel) {
  rel = String(rel || '').replace(/\\/g, '/').replace(/^\/+/, '');
  if (typeof src !== 'string') return { html: src, skip: 'not html' };
  if (isStub(src)) return { html: src, skip: 'stub' };
  let html = src.replace(BLOCK_RE, '');
  const url = urlOf(html, rel);
  html = patchLd(html, url, null);
  if (isNoindex(src)) return { html, skip: 'noindex' };
  const articleAt = html.search(/<article class="tool[ "]/);
  if (articleAt < 0) return { html };
  if (SKIP_PREFIX.some((p) => rel.indexOf(p) === 0)) return { html, skip: 'prefix' };
  const d = C()[url];
  if (!d) return { html };
  const end = html.indexOf('</article>', articleAt);
  if (end < 0) return { html, skip: 'no article end' };
  const from = afterTool(html, articleAt, end);
  if (from < 0) return { html, skip: 'no anchor' };

  const tail = html.slice(articleAt, end);
  const has = {
    steps: STEPS_RE.test(tail),
    tool: /MVRTool\.mountCurrency\(/.test(html) ? 'currency' : /MVRTool\.mount\(/.test(html) ? 'calc' : '',
    own: ownHeadings(tail)
  };
  const where = insertAt(html, from, end);
  const block = where.indent + OPEN + '\n' + where.indent + render(d, has) + '\n' + where.indent + CLOSE;
  html = html.slice(0, where.at) + '\n' + block + html.slice(where.at);
  html = patchLd(html, url, d.faq);
  return { html, depth: 1, faq: (d.faq || []).length, url };
}

/** For generators: the page as this script would leave it. Pure. */
function apply(html, rel) {
  if (typeof html !== 'string') return html;
  return plan(html, rel).html;
}

/* ---------- the stylesheet ---------- */

function patchCss() {
  const frag = path.join(ROOT, 'build', 'site', 'depth.css');
  const abs = path.join(ROOT, 'assets', 'app.css');
  if (!fs.existsSync(frag) || !fs.existsSync(abs)) return false;
  const src = fs.readFileSync(abs, 'utf8');
  const block = fs.readFileSync(frag, 'utf8').trim();
  if (block.indexOf(CSS_OPEN) !== 0 || block.slice(-CSS_CLOSE.length) !== CSS_CLOSE) throw new Error('build-depth.js: build/site/depth.css must start with ' + CSS_OPEN + ' and end with ' + CSS_CLOSE);
  let next;
  const a = src.indexOf(CSS_OPEN);
  if (a >= 0) {
    const b = src.indexOf(CSS_CLOSE, a);
    if (b < 0) throw new Error('build-depth.js: unterminated ' + CSS_OPEN + ' in assets/app.css');
    next = src.slice(0, a) + block + src.slice(b + CSS_CLOSE.length);
  } else {
    const p = src.indexOf(CSS_AFTER);
    next = p >= 0
      ? src.slice(0, p + CSS_AFTER.length) + '\n' + block + src.slice(p + CSS_AFTER.length)
      : src.trimEnd() + '\n' + block + '\n';
  }
  next = withBlock(next, FILES_CSS_OPEN, FILES_CSS_CLOSE, FILES_CSS, CSS_CLOSE);
  if (next === src) return false;
  if (!CHECK) fs.writeFileSync(abs, next);
  return true;
}

/* The file and text tools' "How it works in your browser": the method as a
   numbered list in the formula's highlighted box. Kept here rather than in
   build/site/depth.css so that fragment, and every calculator page, stays
   exactly as it was; it sits in app.css straight after the D7 block. */
const FILES_CSS_OPEN = '/* ==== D7-depth-files ==== */';
const FILES_CSS_CLOSE = '/* ==== /D7-depth-files ==== */';
const FILES_CSS = [
  FILES_CSS_OPEN,
  '/* Written by build-depth.js: the method a file or text tool uses, step by step. */',
  '.depth-points {',
  '  list-style: none; counter-reset: depth-pt; margin: 16px 0 0; padding: 6px 18px;',
  '  border-radius: var(--radius-sm); background: color-mix(in srgb, var(--accent) 7%, var(--bg-0));',
  '  border: 1px solid var(--border-gold); border-left: 4px solid var(--accent);',
  '}',
  '.depth-points li {',
  '  counter-increment: depth-pt; position: relative; padding: 10px 0 10px 34px;',
  '  font-size: .97rem; line-height: 1.62; color: var(--text-2); overflow-wrap: break-word;',
  '}',
  '.depth-points li + li { border-top: 1px dashed var(--border); }',
  '.depth-points li::before {',
  '  content: counter(depth-pt); position: absolute; left: 0; top: 11px; display: grid; place-items: center;',
  '  width: 22px; height: 22px; border-radius: 50%; font: 700 .76rem/1 var(--font-body);',
  '  color: var(--accent); background: var(--bg-0); border: 1px solid var(--border-gold);',
  '}',
  '.depth-works code, .depth-points code {',
  '  font: 500 .9em/1.4 var(--font-mono); color: var(--text-1); overflow-wrap: anywhere;',
  '  padding: 1px 5px; border-radius: 4px; background: var(--bg-0); border: 1px solid var(--border);',
  '}',
  '@media (max-width: 640px) {',
  '  .depth-points { padding: 4px 14px; }',
  '  .depth-points li { padding-left: 30px; font-size: .95rem; }',
  '}',
  FILES_CSS_CLOSE
].join('\n');

/** src with exactly one copy of block between open and close, placed after `after` when new. */
function withBlock(src, open, close, block, after) {
  const a = src.indexOf(open);
  if (a >= 0) {
    const b = src.indexOf(close, a);
    if (b < 0) throw new Error('build-depth.js: unterminated ' + open + ' in assets/app.css');
    return src.slice(0, a) + block + src.slice(b + close.length);
  }
  const p = src.indexOf(after);
  return p >= 0
    ? src.slice(0, p + after.length) + '\n' + block + src.slice(p + after.length)
    : src.trimEnd() + '\n' + block + '\n';
}

/* ---------- the walk (build-proof.js's) ---------- */

function pages() {
  const out = [];
  (function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      if (SKIP_DIRS.has(name)) continue;
      const abs = path.join(dir, name);
      if (fs.statSync(abs).isDirectory()) walk(abs);
      else if (name.endsWith('.html')) out.push(abs);
    }
  })(ROOT);
  return out;
}

function unpublished() {
  const out = new Set();
  try {
    require('child_process')
      .execFileSync('git', ['ls-files', '--others', '--exclude-standard'],
        { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26, stdio: ['ignore', 'pipe', 'ignore'] })
      .split('\n').forEach(function (f) {
        const t = f.trim();
        if (t.endsWith('.html')) out.add(t);
      });
  } catch (e) { /* no git: treat everything as published */ }
  return out;
}

function bumpServiceWorker() {
  const abs = path.join(ROOT, 'sw.js');
  if (!fs.existsSync(abs)) return false;
  const src = fs.readFileSync(abs, 'utf8');
  const next = src.replace(/var V = '1234tools-v(\d+)';/, function (m, n) {
    return "var V = '1234tools-v" + (Number(n) + 1) + "';";
  });
  if (next === src) return false;
  if (!CHECK) fs.writeFileSync(abs, next);
  return true;
}

function main() {
  const drafts = unpublished();
  const files = [];
  const skipped = {};
  const seen = new Set();
  let scanned = 0, written = 0, questions = 0;
  for (const abs of pages()) {
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (drafts.has(rel)) { (skipped.draft = skipped.draft || []).push(rel); continue; }
    if (rel.indexOf('conversions/') === 0) continue;
    scanned++;
    const before = fs.readFileSync(abs, 'utf8');
    const p = plan(before, rel);
    if (p.depth) { written++; questions += p.faq; seen.add(p.url); }
    if (p.skip && p.skip !== 'noindex' && p.skip !== 'stub' && C()[urlOf(before, rel)]) (skipped[p.skip] = skipped[p.skip] || []).push(rel);
    if (p.html !== before) {
      files.push(rel);
      if (!CHECK) fs.writeFileSync(abs, p.html);
    }
  }
  const css = patchCss();
  const missing = Object.keys(C()).filter((u) => !seen.has(u));
  const sw = files.length || css ? bumpServiceWorker() : false;

  console.log('\nbuild-depth.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  pages scanned       ' + scanned + ' (conversions left alone)');
  console.log('  content entries     ' + Object.keys(C()).length);
  console.log('  depth blocks        ' + written + ' (' + questions + ' questions merged into FAQPage)');
  if (missing.length) console.log('  content, no page    ' + missing.length + '   ' + missing.slice(0, 8).join(', '));
  Object.keys(skipped).sort().forEach(function (k) {
    console.log('  skipped: ' + (k + ' ').padEnd(16) + String(skipped[k].length).padStart(5) + '   ' + skipped[k].slice(0, 8).join(', '));
  });
  console.log('  app.css             ' + (css ? (CHECK ? 'would update' : 'updated') : 'unchanged'));
  console.log('  service worker      ' + (sw ? (CHECK ? 'would bump' : 'bumped') : 'unchanged'));
  if (VERBOSE) files.slice(0, 80).forEach(function (f) { console.log('    ' + f); });
  console.log('\n  ' + files.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

if (require.main === module) main();
module.exports = { apply, plan, render, OPEN, CLOSE, content: C };
