/**
 * The share bar on every tool page, and a preview card for every share.
 *
 *   node build-share.js            apply
 *   node build-share.js --check    report what would change, write nothing
 *   node build-share.js --verbose  list the files
 *
 * Three edits, each marker-delimited and a pure function of the page:
 *
 * 1. A placeholder in the body, which assets/share.js fills in:
 *
 *      <!-- SHARE: generated by build-share.js, do not edit -->
 *      <div class="share" data-share data-share-kind="calc"
 *           data-share-sec="finance" data-share-slug="compound-interest" hidden></div>
 *      <!-- /SHARE -->
 *
 *    after the calculator (.calc) or the tool's .tool-io on every
 *    article.tool page, and before </article> on every article.collection
 *    page (/for/, /guides/, /compare/, /hi/for/). The kind comes from the
 *    page's own mount call; the section and slug from its canonical, never
 *    from data-tool, which 1,048 conversion pages do not carry.
 *
 * 2. Beside the preferences tag in the head, on the same pages only:
 *    a one-line inline script that marks ?embed=1 before the body parses
 *    (no flash of header inside somebody's iframe), and share.js, deferred.
 *
 * 3. On every published page, rows or not: og:image points at the most
 *    specific card build/make-og.js --cards made for the page's path
 *    (tool, then conversion family, then section, then the site card), with
 *    its width, height, type and alt, and twitter:image to match.
 *
 * Redirect stubs and unpublished drafts are left alone; noindex pages, the
 * home page and /practice/, /account/, /pwa/, /learn/ get the og tags but no
 * row. The
 * walk, the --check mode and the service-worker bump are build-outbound's.
 *
 * Like build-prefs and build-outbound, apply(html, rel) is also lent to the
 * generators, which call it at write time; a generator that did not would
 * have its page rewritten here on every run and back on the next.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { SECTIONS } = require('./build/sections.js');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const VERBOSE = process.argv.includes('--verbose');
const SITE = 'https://www.1234tools.com';
const SITE_CARD = '/assets/img/og-image.png';
const OG_DIR = path.join(ROOT, 'assets', 'img', 'og');

const STATE_MARKERS = {
  row: '<!-- SHARE: generated by build-share.js, do not edit -->',
  rowEnd: '<!-- /SHARE -->',
  head: '<!-- SHARE-HEAD: generated by build-share.js, do not edit -->',
  headEnd: '<!-- /SHARE-HEAD -->'
};

/* Every page has this tag: build-prefs.js puts it there and throws if it
   cannot. The head block goes directly after it. */
const HEAD_ANCHOR = '<script src="/assets/prefs.js" defer></script>';
const EMBED_FLAG = "<script>if(/[?&]embed=1(?:&|$)/.test(location.search))document.documentElement.classList.add('is-embed');</script>";

/* Pages whose figures are somebody's pay. Their "Include my figures" box says
   so in one line, because a link with a salary in it is a salary sent. */
const PAY = new Set([
  'business/uk-take-home-pay', 'business/employer-cost', 'business/ctc-structure',
  'business/full-final-settlement', 'business/payroll-run', 'business/vat-return',
  'business/mtd-checker', 'business/mtd-quarterly-update',
  'india/india-income-tax', 'india/advance-tax', 'india/hra-exemption', 'india/epf-calculator',
  'india/gratuity-calculator', 'india/ctc-take-home',
  'pdf/payslip-pdf', 'ai/form16-reader'
]);

/* Not tool pages, whatever their markup says. */
const SKIP_PREFIX = ['practice/', 'account/', 'pwa/', 'learn/'];
const NO_ROW = new Set(['index.html', '404.html']);
const SKIP_DIRS = new Set(['node_modules', '.git', 'build']);

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const unesc = (s) => String(s)
  .replace(/&(?:lt|#0*60);/g, '<').replace(/&(?:gt|#0*62);/g, '>')
  .replace(/&(?:quot|#0*34);/g, '"').replace(/&(?:#0*39|apos|#x27);/g, "'")
  .replace(/&nbsp;/g, ' ').replace(/&(?:amp|#0*38);/g, '&');

const isStub = (html) => /name="robots" content="noindex/.test(html) && /http-equiv="refresh"/.test(html);
const isNoindex = (html) => /<meta name="robots" content="noindex/.test(html);

function pages() {
  const out = [];
  (function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      if (SKIP_DIRS.has(name)) continue;
      const abs = path.join(dir, name);
      if (fs.statSync(abs).isDirectory()) walk(abs);
      else if (name.endsWith('.html')) out.push(abs);
    }
  })(ROOT);
  return out;
}

/** Untracked HTML is somebody's unfinished work; it is not ours to rewrite. */
function unpublished() {
  const out = new Set();
  try {
    require('child_process')
      .execFileSync('git', ['ls-files', '--others', '--exclude-standard'],
        { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26, stdio: ['ignore', 'pipe', 'ignore'] })
      .split('\n').forEach(function (f) {
        const t = f.trim();
        if (t.endsWith('.html')) out.add(t);
      });
  } catch (e) { /* no git: treat everything as published */ }
  return out;
}

/** The page's own URL, from the canonical it already declares. */
function urlOf(html, rel) {
  const m = /<link rel="canonical" href="([^"]+)"/.exec(html);
  if (m) return m[1].replace(SITE, '').replace(/[?#].*$/, '') || '/';
  return '/' + rel.replace(/index\.html$/, '').replace(/\.html$/, '/');
}

/* ---------- og cards ---------- */

let cardCache = null;
/** Every card make-og.js --cards has written, as paths under assets/img/og/. */
function loadCards() {
  if (cardCache) return cardCache;
  const set = new Set();
  if (fs.existsSync(OG_DIR)) {
    (function walk(dir, pre) {
      for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
        if (ent.isDirectory()) walk(path.join(dir, ent.name), pre + ent.name + '/');
        else if (ent.name.endsWith('.jpg')) set.add(pre + ent.name);
      }
    })(OG_DIR, '');
  }
  cardCache = set;
  return set;
}

/**
 * The most specific card along the page's own path:
 *   /conversions/length/angstrom-to-centimeter/ → og/conversions/length/angstrom-to-centimeter.jpg
 *   → og/conversions/length.jpg → og/conversions.jpg → the site card.
 */
function cardFor(urlPath, cards) {
  cards = cards || loadCards();
  const parts = String(urlPath).split('/').filter(Boolean);
  for (let i = Math.min(parts.length, 3); i > 0; i--) {
    const key = parts.slice(0, i).join('/') + '.jpg';
    if (cards.has(key)) {
      const level = i === 1 ? 'section' : (parts[0] === 'conversions' && i === 2 ? 'family' : 'tool');
      return { url: '/assets/img/og/' + key, type: 'image/jpeg', level };
    }
  }
  return { url: SITE_CARD, type: 'image/png', level: 'site' };
}

function h1Of(html) {
  const m = /<h1[^>]*>([\s\S]*?)<\/h1>/.exec(html);
  return m ? unesc(m[1].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim()) : '';
}

/** The page's own name: its last breadcrumb, then its h1, then its title. */
function labelOf(html) {
  const crumb = /<nav class="crumbs"[^>]*>([\s\S]*?)<\/nav>/.exec(html);
  if (crumb) {
    const cur = /<span aria-current="page">([\s\S]*?)<\/span>/.exec(crumb[1]);
    if (cur) {
      const t = unesc(cur[1].replace(/<[^>]*>/g, '').trim());
      if (t) return t;
    }
  }
  const h = h1Of(html);
  if (h) return h;
  const t = /<title>([^<]*)<\/title>/.exec(html);
  return t ? unesc(t[1].split('|')[0].split('—')[0].trim()) : '1234Tools';
}

function altFor(html, url, isTool) {
  if (isTool) {
    const name = h1Of(html) || labelOf(html);
    return url.indexOf('/ai/') === 0
      ? name + ' — free to try, cloud AI. 1234Tools'
      : name + ' — free, runs in your browser. 1234Tools';
  }
  return labelOf(html) + ' — 1234Tools';
}

const OG_IMG = /<meta property="og:image" content="[^"]*">/;
const OG_EXTRA = /<meta property="og:image:(?:width|height|type|alt)" content="[^"]*">\n?/g;
const TW_IMG = /<meta name="twitter:image" content="[^"]*">\n?/g;
const TW_CARD = /<meta name="twitter:card" content="[^"]*">/;

function rewriteOg(html, url, isTool, cards) {
  if (!OG_IMG.test(html)) return { html, level: null };
  const card = cardFor(url, cards);
  const abs = SITE + card.url;
  const block =
    '<meta property="og:image" content="' + abs + '">\n' +
    '<meta property="og:image:width" content="1200">\n' +
    '<meta property="og:image:height" content="630">\n' +
    '<meta property="og:image:type" content="' + card.type + '">\n' +
    '<meta property="og:image:alt" content="' + esc(altFor(html, url, isTool)) + '">';
  const tw = '<meta name="twitter:image" content="' + abs + '">';
  let h = html.replace(OG_EXTRA, '').replace(TW_IMG, '');
  h = h.replace(OG_IMG, function () { return block; });
  if (TW_CARD.test(h)) h = h.replace(TW_CARD, function (m) { return m + '\n' + tw; });
  else h = h.replace(block, function () { return block + '\n' + tw; });
  return { html: h, level: card.level };
}

/* ---------- the row ---------- */

const ROW_RE = /\n[ \t]*<!-- SHARE: generated by build-share\.js, do not edit -->[\s\S]*?<!-- \/SHARE -->/g;
const HEAD_RE = /\n<!-- SHARE-HEAD: generated by build-share\.js, do not edit -->[\s\S]*?<!-- \/SHARE-HEAD -->/g;
const CALC_RE = /<div class="calc">[\s\S]*?<div class="tool-results"[^>]*><\/div>\s*<\/div>/;
const IO_RE = /<div class="tool-io"(?: [^>]*)?><\/div>/;

/** What the page mounts, read from its own inline script. */
function kindOf(html) {
  if (/<article class="collection/.test(html)) return 'page';
  if (!/<article class="tool/.test(html)) return null;
  if (/MVRTool\.mount\(/.test(html)) return 'calc';
  if (/mountConverter\(/.test(html)) return 'converter';
  if (/mountCurrency\(/.test(html)) return 'currency';
  if (/mountCode\(/.test(html)) return 'code';
  if (/mountQR\(/.test(html)) return 'qr';
  return 'io';
}

/** utm_campaign and utm_content: the first path segment, and the rest. */
function secSlug(url) {
  const parts = url.split('/').filter(Boolean);
  return { sec: parts[0] || 'home', slug: parts.slice(1).join('/') || 'index' };
}

function rowBlock(kind, sec, slug) {
  const warn = PAY.has(sec + '/' + slug) ? ' data-share-warn="pay"' : '';
  return STATE_MARKERS.row + '\n' +
    '  <div class="share' + (kind === 'page' ? ' share-page' : '') + '" data-share data-share-kind="' + kind +
    '" data-share-sec="' + esc(sec) + '" data-share-slug="' + esc(slug) + '"' + warn + ' hidden></div>\n' +
    '  ' + STATE_MARKERS.rowEnd;
}

const HEAD_BLOCK = STATE_MARKERS.head + '\n' + EMBED_FLAG + '\n' +
  '<script src="/assets/share.js" defer></script>\n' + STATE_MARKERS.headEnd;

function insertRow(html, kind, block) {
  if (kind === 'calc' || kind === 'converter') {
    if (CALC_RE.test(html)) return html.replace(CALC_RE, function (m) { return m + '\n  ' + block; });
    if (!IO_RE.test(html)) return null;
  }
  if (kind === 'page') {
    const at = html.lastIndexOf('</article>');
    if (at < 0) return null;
    const cut = html[at - 1] === '\n' ? at - 1 : at;
    return html.slice(0, cut) + '\n  ' + block + html.slice(cut);
  }
  if (!IO_RE.test(html)) return null;
  return html.replace(IO_RE, function (m) { return m + '\n  ' + block; });
}

/**
 * Everything this script decides about one page.
 * Returns { html, kind, skip, level, unknown }.
 */
function plan(src, rel, cards) {
  rel = String(rel || '').replace(/\\/g, '/');
  if (isStub(src)) return { html: src, skip: 'stub' };

  /* A noindex page gets no row, but its og tags are still normalised: the
     generators build those pages from a tool page's head, and leaving the
     copied card in place would name the wrong tool. */
  let html = src.replace(ROW_RE, '').replace(HEAD_RE, '');
  if (isNoindex(src)) {
    const og0 = rewriteOg(html, urlOf(html, rel), false, cards);
    return { html: og0.html, skip: 'noindex', level: og0.level };
  }
  const url = urlOf(html, rel);
  const kind0 = kindOf(html);
  const prefixed = SKIP_PREFIX.some(function (p) { return rel.indexOf(p) === 0; });
  const og = rewriteOg(html, url, !!kind0 && kind0 !== 'page' && !prefixed, cards);
  html = og.html;

  let skip = null;
  if (NO_ROW.has(rel)) skip = 'root';
  else if (prefixed) skip = 'prefix';
  else if (!kind0) skip = 'no article';
  if (skip) return { html, skip, level: og.level };

  const { sec, slug } = secSlug(url);
  const known = !!(SECTIONS['/' + sec + '/'] || (sec === 'hi' && SECTIONS['/hi/for/']));
  const withRow = insertRow(html, kind0, rowBlock(kind0, sec, slug));
  if (withRow === null) return { html, skip: 'no anchor', level: og.level };
  if (withRow.indexOf(HEAD_ANCHOR) < 0) return { html, skip: 'no head anchor', level: og.level };
  html = withRow.replace(HEAD_ANCHOR, function (m) { return m + '\n' + HEAD_BLOCK; });
  return { html, kind: kind0, level: og.level, unknown: known ? null : sec };
}

/**
 * For generators: the page as this script would leave it. Pure; reads the
 * card list from disk once per process.
 */
function apply(html, rel, cards) {
  if (typeof html !== 'string') return html;
  return plan(html, rel, cards).html;
}

/* Pages changed, so returning visitors must be told to refetch rather than
   keep serving the old shell out of the cache. */
function bumpServiceWorker() {
  const abs = path.join(ROOT, 'sw.js');
  if (!fs.existsSync(abs)) return false;
  const src = fs.readFileSync(abs, 'utf8');
  const next = src.replace(/var V = '1234tools-v(\d+)';/, function (m, n) {
    return "var V = '1234tools-v" + (Number(n) + 1) + "';";
  });
  if (next === src) return false;
  if (!CHECK) fs.writeFileSync(abs, next);
  return true;
}

function main() {
  const drafts = unpublished();
  const cards = loadCards();
  const rows = {}, skipped = {}, levels = {}, unknown = new Set();
  const files = [];
  let scanned = 0;

  for (const abs of pages()) {
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (drafts.has(rel)) { (skipped.draft = skipped.draft || []).push(rel); continue; }
    scanned++;
    const before = fs.readFileSync(abs, 'utf8');
    const p = plan(before, rel, cards);
    if (p.kind) rows[p.kind] = (rows[p.kind] || 0) + 1;
    if (p.skip) (skipped[p.skip] = skipped[p.skip] || []).push(rel);
    if (p.level) levels[p.level] = (levels[p.level] || 0) + 1;
    if (p.unknown) unknown.add(p.unknown);
    if (p.html !== before) {
      files.push(rel);
      if (!CHECK) fs.writeFileSync(abs, p.html);
    }
  }

  const sw = files.length ? bumpServiceWorker() : false;
  const total = Object.values(rows).reduce(function (a, b) { return a + b; }, 0);

  console.log('\nbuild-share.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  pages scanned       ' + scanned);
  console.log('  og cards on disk    ' + cards.size);
  console.log('  share rows          ' + total + ' (' + Object.entries(rows).sort().map(function (k) { return k[0] + ' ' + k[1]; }).join(', ') + ')');
  console.log('  og:image by level   ' + Object.entries(levels).sort().map(function (k) { return k[0] + ' ' + k[1]; }).join(', '));
  Object.keys(skipped).sort().forEach(function (k) {
    const list = skipped[k];
    console.log('  skipped: ' + (k + ' ').padEnd(16) + String(list.length).padStart(5) +
      (k === 'no anchor' || k === 'no head anchor' || VERBOSE ? '   ' + list.slice(0, 8).join(', ') : ''));
  });
  if (unknown.size) console.log('  ! sections not in build/sections.js: ' + Array.from(unknown).join(', '));
  console.log('  service worker      ' + (sw ? (CHECK ? 'would bump' : 'bumped') : 'unchanged'));
  if (VERBOSE) files.slice(0, 40).forEach(function (f) { console.log('    ' + f); });
  console.log('\n  ' + files.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

if (require.main === module) main();
module.exports = { apply, cardFor, STATE_MARKERS, PAY };
