/**
 * Generate /learn/ — the curated directory of outside learning resources.
 *
 *   node build-learn.js          apply
 *   node build-learn.js --check  report what would change, write nothing
 *
 * One hub page and one page per category, built from build/learn-data.js and
 * wrapped in the same shell as the rest of the site.
 *
 * Two deliberate differences from every other section here.
 *
 * These pages are not tools, so they stay out of assets/search-index.js. That
 * file drives the tool count, the per-tool manifests and the related-tool
 * graph, and a link directory belongs in none of them. Calling this site
 * "1,198 free tools" when eleven of them are lists of somebody else's work
 * would be a small lie told 2,400 times.
 *
 * And the links are rendered into the HTML at build time rather than fetched
 * by script. A directory whose contents only exist after JavaScript runs is
 * invisible to a crawler and useless offline, which would defeat the point of
 * publishing it.
 *
 * Run build/check-links.js before this. It is not called automatically,
 * because generating pages should not depend on 103 other people's servers
 * being up at that moment.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { CATEGORIES } = require('./build/learn-data.js');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const SITE = 'https://www.1234tools.com';

const changes = [];
function write(rel, content) {
  const abs = path.join(ROOT, rel);
  const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (existing === content) return false;
  changes.push((existing === null ? 'create ' : 'update ') + rel);
  if (!CHECK) {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
  }
  return true;
}

const esc = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  .replace(/"/g, '&quot;');

/* ------------------------------------------------------------------ */
/* the shell                                                          */
/* ------------------------------------------------------------------ */

/**
 * Everything around the content, lifted from a page that already has it.
 *
 * Copying the shell rather than templating it is what keeps these pages
 * identical to the other 1,187 — the header, the sidebar, the consent banner
 * and the generated font and analytics blocks all arrive correct by
 * construction, and stay correct when build-site.js next edits them.
 */
function shell() {
  const src = fs.readFileSync(path.join(ROOT, 'qr/index.html'), 'utf8');
  const headEnd = src.indexOf('</head>');
  const mainStart = src.indexOf('<main id="main" class="content">');
  const mainEnd = src.indexOf('</main>');
  if (headEnd < 0 || mainStart < 0 || mainEnd < 0) throw new Error('could not read the shell from qr/index.html');
  return {
    head: src.slice(0, headEnd),
    betweenHeadAndMain: src.slice(headEnd, mainStart + '<main id="main" class="content">'.length),
    tail: src.slice(mainEnd)
  };
}

/** Swap the parts of the head that are specific to one page. */
function head(parts, title, description, canonical) {
  let h = parts.head
    .replace(/<title>[^<]*<\/title>/, '<title>' + esc(title) + '</title>')
    .replace(/<meta name="description" content="[^"]*">/, '<meta name="description" content="' + esc(description) + '">')
    .replace(/<link rel="canonical" href="[^"]*">/, '<link rel="canonical" href="' + canonical + '">')
    .replace(/<meta property="og:title" content="[^"]*">/, '<meta property="og:title" content="' + esc(title) + '">')
    .replace(/<meta property="og:description" content="[^"]*">/, '<meta property="og:description" content="' + esc(description) + '">')
    .replace(/<meta property="og:url" content="[^"]*">/, '<meta property="og:url" content="' + canonical + '">')
    .replace(/<meta name="twitter:title" content="[^"]*">/, '<meta name="twitter:title" content="' + esc(title) + '">')
    .replace(/<meta name="twitter:description" content="[^"]*">/, '<meta name="twitter:description" content="' + esc(description) + '">');

  /* No per-tool manifest. A directory of links is not something to install as
     its own app, and offering it would cheapen the offer on the tools that do
     genuinely work offline. These pages still carry the site-wide
     manifest.webmanifest, the same as every other section hub. The shell is
     taken from a hub and so has no per-tool block to remove, making this belt
     and braces — but the rule belongs here rather than in the choice of shell. */
  h = h.replace(/<!-- PWA: generated by build-pwa\.js, do not edit -->[\s\S]*?<!-- \/PWA -->\n?/, '');
  /* And no tool JSON-LD — these are collections, described below instead. */
  h = h.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>\n?/, '');
  return h;
}

/**
 * Nothing borrowed from the shell is the current page, and the Learning entry
 * is. Doing both here rather than leaving the second to the sidebar patch is
 * what makes a rebuild idempotent: generation now produces the final markup
 * instead of a state the patch has to correct afterwards.
 */
const clearActive = (html) =>
  html.replace(/ class="side-link is-active"/g, ' class="side-link"')
      .replace('<a class="side-link" href="/learn/">', '<a class="side-link is-active" href="/learn/">');

function jsonLd(obj) {
  return '<script type="application/ld+json">' + JSON.stringify(obj) + '</script>\n';
}

/* ------------------------------------------------------------------ */
/* pages                                                              */
/* ------------------------------------------------------------------ */

const COST_LABEL = { free: 'Free', 'free-tier': 'Free tier', paid: 'Paid' };

const icon = (id) =>
  '<svg class="ico" aria-hidden="true" focusable="false"><use href="/assets/icons.svg#' + id + '"></use></svg>';

function linkRow(link) {
  const [title, url, provider, cost, note] = link;
  let host;
  try { host = new URL(url).hostname.replace(/^www\./, ''); } catch (e) { host = ''; }
  return '<li class="learn-item">' +
    '<div class="learn-item-head">' +
      /* Opened in a new tab because people arrive here mid-task and the list
         is something to come back to. noopener because target=_blank without
         it hands the new page a handle on this one. */
      '<a class="learn-title" href="' + esc(url) + '" target="_blank" rel="noopener">' + esc(title) + '</a>' +
      '<span class="learn-cost is-' + cost + '">' + COST_LABEL[cost] + '</span>' +
    '</div>' +
    '<p class="learn-note">' + esc(note) + '</p>' +
    '<p class="learn-meta"><span class="learn-provider">' + esc(provider) + '</span>' +
      (host ? '<span class="learn-host">' + esc(host) + '</span>' : '') + '</p>' +
  '</li>';
}

function categoryPage(cat, parts) {
  const url = SITE + '/learn/' + cat.slug + '/';
  const title = cat.name + ' — Learning Resources | 1234Tools';
  const counts = cat.links.reduce(function (n, l) { n[l[3]] = (n[l[3]] || 0) + 1; return n; }, {});
  const free = (counts.free || 0);
  const description = cat.links.length + ' hand-picked ' + cat.name.toLowerCase() +
    ' courses, references and practice sites, ' + free + ' of them free. What each one is, who made it, and what it costs.';

  const body =
    '<nav class="crumbs"><a href="/">Home</a> › <a href="/learn/">Learning</a> › <span>' + esc(cat.name) + '</span></nav>\n' +
    '<article class="tool">\n' +
    '  <p class="eyebrow">Learning</p>\n' +
    '  <h1><svg class="ico ico-title" aria-hidden="true" focusable="false"><use href="/assets/icons.svg#' + cat.icon + '"></use></svg>' + esc(cat.name) + '</h1>\n' +
    '  <p class="lede">' + esc(cat.blurb) + '</p>\n' +
    '  <section class="panel learn-guidance"><h2>Where to start</h2><p>' + esc(cat.guidance) + '</p></section>\n' +
    '  <ul class="learn-list">' + cat.links.map(linkRow).join('') + '</ul>\n' +
    '  <section class="panel"><h2>About this list</h2><p class="privacy-line">' +
      cat.links.length + ' resources, checked automatically every week so dead links do not sit here unnoticed. ' +
      'Nothing on this page is sponsored and none of these links pay us — which is the only reason a recommendation on it is worth anything. ' +
      'Every link goes to the original source, and we take nothing with you when you leave.' +
    '</p></section>\n' +
    '  <section class="panel"><h2>Other subjects</h2><ul class="related">' +
      CATEGORIES.filter(function (c) { return c.slug !== cat.slug; })
        .map(function (c) { return '<li><a href="/learn/' + c.slug + '/">' + esc(c.name) + '</a></li>'; }).join('') +
    '</ul></section>\n' +
    '</article>\n';

  const ld = jsonLd({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CollectionPage', name: cat.name + ' learning resources',
        description: description, url: url,
        /* ItemList rather than pretending each link is our content. */
        mainEntity: {
          '@type': 'ItemList', numberOfItems: cat.links.length,
          itemListElement: cat.links.map(function (l, i) {
            return { '@type': 'ListItem', position: i + 1, name: l[0], url: l[1] };
          })
        }
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: SITE },
          { '@type': 'ListItem', position: 2, name: 'Learning', item: SITE + '/learn/' },
          { '@type': 'ListItem', position: 3, name: cat.name, item: url }
        ]
      }
    ]
  });

  return clearActive(head(parts, title, description, url) + ld + parts.betweenHeadAndMain + '\n' + body + parts.tail);
}

function hubPage(parts) {
  const url = SITE + '/learn/';
  const total = CATEGORIES.reduce(function (n, c) { return n + c.links.length; }, 0);
  const title = 'Learning Resources — Curated Courses, Labs & Practice | 1234Tools';
  const description = total + ' hand-picked places to learn, across ' + CATEGORIES.length +
    ' subjects: AI, programming, data, cloud, security, labs, mock interviews and certifications. No affiliate links, checked weekly.';

  const cards = CATEGORIES.map(function (c) {
    return '<a class="card" href="/learn/' + c.slug + '/">' +
      '<span class="card-icon">' + icon(c.icon) + '</span>' +
      '<strong>' + esc(c.name) + '</strong>' +
      '<span class="card-desc">' + esc(c.blurb) + '</span>' +
      '<span class="card-count">' + c.links.length + ' resources</span>' +
    '</a>';
  }).join('');

  const body =
    '<nav class="crumbs"><a href="/">Home</a> › <span>Learning</span></nav>\n' +
    '<p class="eyebrow">Learning</p>\n' +
    '<h1><svg class="ico ico-title" aria-hidden="true" focusable="false"><use href="/assets/icons.svg#i-learn"></use></svg>Learning Resources</h1>\n' +
    '<p class="lede">' + total + ' places to actually learn something, across ' + CATEGORIES.length +
      ' subjects. Every one is somebody else’s work and we say so.</p>\n' +
    /* Say what this is, and what it is not. The rest of the site is tools that
       run on your device; this page is a set of front doors to other people's
       work, and pretending otherwise would be the wrong kind of clever. */
    '<section class="panel learn-guidance"><h2>What this is</h2>' +
      '<p>The rest of this site is tools that run on your own device. This part is different: it is a reading list, ' +
      'and every link on it leads somewhere else.</p>' +
      '<p>It is kept short on purpose. Anyone can paste five hundred links; the useful thing is knowing which ten to ' +
      'open first and why, so each subject opens with that and each entry says what it actually is, who made it, and ' +
      'what it costs before you click.</p>' +
      '<p><strong>Nothing here is sponsored and no link pays us a penny.</strong> Primary sources are preferred — ' +
      'universities, standards bodies, the people who wrote the language — because those go stale slowest. ' +
      'Everything is re-checked automatically every week, so a dead link gets found by us rather than by you.</p>' +
    '</section>\n' +
    '<div class="grid learn-grid">' + cards + '</div>\n' +
    '<section class="panel"><h2>Looking for something that does the work?</h2>' +
      '<p>The ' + '1,187' + ' calculators and converters on the rest of this site all run in your browser, with nothing uploaded. ' +
      'Start from <a href="/">all tools</a>, or the <a href="/developer/">developer</a>, <a href="/india/">India</a> and ' +
      '<a href="/business/">business</a> sections.</p>' +
    '</section>\n';

  const ld = jsonLd({
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'CollectionPage', name: 'Learning Resources', description: description, url: url,
        mainEntity: {
          '@type': 'ItemList', numberOfItems: CATEGORIES.length,
          itemListElement: CATEGORIES.map(function (c, i) {
            return { '@type': 'ListItem', position: i + 1, name: c.name, url: SITE + '/learn/' + c.slug + '/' };
          })
        }
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: SITE },
          { '@type': 'ListItem', position: 2, name: 'Learning', item: url }
        ]
      }
    ]
  });

  return clearActive(head(parts, title, description, url) + ld + parts.betweenHeadAndMain + '\n' + body + parts.tail);
}

/* ------------------------------------------------------------------ */
/* the homepage card and the sitemap                                  */
/* ------------------------------------------------------------------ */

const HOME_START = '<!-- LEARN: generated by build-learn.js, do not edit -->';
const HOME_END = '<!-- /LEARN -->';

/**
 * The sidebar entry, in a group of its own.
 *
 * Not in "Categories". That list is tool categories with tool counts, and
 * "Learning 103" sitting between "PDF Tools 16" and "QR Tools 3" would read as
 * a hundred and three tools. Its own heading says what it is without a count
 * having to carry the distinction.
 *
 * One link from every page rather than one from the whole site, which is what
 * the homepage card was managing on its own.
 */
function patchSidebar(total) {
  const group =
    '\n      <p class="side-group">Learning</p>\n' +
    '      <a class="side-link" href="/learn/">\n' +
    '        ' + icon('i-learn') + '<span class="side-name">Learning resources</span>' +
    '<span class="side-count">' + total + '</span>\n' +
    '      </a>\n';

  /* Before the conversion families, so it sits after every tool category and
     before the long tail of unit pages. */
  const anchor = '\n      <p class="side-group">Conversion families</p>';

  const drafts = unpublished();
  let touched = 0, skipped = 0;
  for (const abs of pages()) {
    const rel = path.relative(ROOT, abs).replace(/\\/g, '/');
    if (drafts.has(rel)) { skipped++; continue; }
    const before = fs.readFileSync(abs, 'utf8');
    if (isStub(before) || before.indexOf(anchor) < 0) { skipped++; continue; }

    let html = before;
    const has = /class="side-link[^"]*" href="\/learn\/"/.test(html);
    if (!has) html = html.replace(anchor, group + anchor);

    /* The count moves as the list grows, so keep it in step. */
    html = html.replace(
      /(<a class="side-link[^"]*" href="\/learn\/">[\s\S]{0,300}?<span class="side-count">)\d+(<\/span>)/,
      '$1' + total + '$2');

    /* Current-page highlight on the section's own pages. */
    const own = rel === 'learn/index.html' || rel.indexOf('learn/') === 0;
    if (own) {
      html = html.replace(/ class="side-link is-active"/g, ' class="side-link"');
      html = html.replace('<a class="side-link" href="/learn/">', '<a class="side-link is-active" href="/learn/">');
    }

    if (html !== before) {
      changes.push('update ' + rel);
      if (!CHECK) fs.writeFileSync(abs, html);
      touched++;
    }
  }
  return { touched, skipped };
}

/** Every page in the tree. */
function pages() {
  const out = [];
  (function walk(dir) {
    for (const name of fs.readdirSync(dir)) {
      if (name === 'node_modules' || name === '.git' || name === 'build') continue;
      const abs = path.join(dir, name);
      if (fs.statSync(abs).isDirectory()) walk(abs);
      else if (name.endsWith('.html')) out.push(abs);
    }
  })(ROOT);
  return out;
}

const isStub = (html) =>
  /name="robots" content="noindex,follow"/.test(html) && /http-equiv="refresh"/.test(html);

/** Pages that exist but have never shipped; not ours to edit. */
function unpublished() {
  const out = new Set();
  try {
    const listed = require('child_process')
      .execFileSync('git', ['ls-files', '--others', '--exclude-standard'],
        { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26 });
    listed.split(String.fromCharCode(10)).forEach(function (f) {
      const t = f.trim();
      if (t.endsWith('.html')) out.add(t);
    });
  } catch (e) { /* no git here: assume everything has shipped */ }
  return out;
}

/**
 * One card on the homepage's category grid. That single link is what makes the
 * section reachable — from the page with the most authority on the site, which
 * is the right one link to have if you are only having one.
 */
function patchHome() {
  const rel = 'index.html';
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const total = CATEGORIES.reduce(function (n, c) { return n + c.links.length; }, 0);
  const block = HOME_START +
    '<a class="card card-lg" href="/learn/"><span class="card-icon">' + icon('i-learn') + '</span>' +
    '<strong>Learning</strong><span class="card-desc">' + total + ' curated resources</span></a>' +
    HOME_END;

  let out;
  if (src.includes(HOME_START)) {
    out = src.slice(0, src.indexOf(HOME_START)) + block +
      src.slice(src.indexOf(HOME_END) + HOME_END.length);
  } else {
    /* After the last category card, so the grid reads tools first. */
    const anchor = /<a class="card card-lg" href="\/design\/">[\s\S]*?<\/a>/;
    const m = anchor.exec(src);
    if (!m) return { patched: false, why: 'no anchor card on the homepage' };
    out = src.slice(0, m.index + m[0].length) + block + src.slice(m.index + m[0].length);
  }
  return { patched: write(rel, out) };
}

function patchSitemap() {
  const rel = 'sitemap-1.xml';
  const src = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  const urls = ['/learn/'].concat(CATEGORIES.map(function (c) { return '/learn/' + c.slug + '/'; }));
  const entries = urls
    .filter(function (u) { return !src.includes('<loc>' + SITE + u + '</loc>'); })
    .map(function (u) {
      return '<url><loc>' + SITE + u + '</loc><changefreq>monthly</changefreq><priority>' +
        (u === '/learn/' ? '0.7' : '0.6') + '</priority></url>';
    });
  if (!entries.length) return 0;
  const out = src.replace('</urlset>', entries.join('\n') + '\n</urlset>');
  write(rel, out);
  return entries.length;
}

/* ------------------------------------------------------------------ */

function main() {
  const parts = shell();
  let pages = 0;
  if (write('learn/index.html', hubPage(parts))) pages++;
  for (const cat of CATEGORIES) {
    if (write('learn/' + cat.slug + '/index.html', categoryPage(cat, parts))) pages++;
  }
  const home = patchHome();
  const added = patchSitemap();
  const total = CATEGORIES.reduce(function (n, c) { return n + c.links.length; }, 0);
  const nav = patchSidebar(total);

  console.log('\nbuild-learn.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  console.log('  categories          ' + CATEGORIES.length);
  console.log('  resources           ' + total);
  console.log('  pages               ' + pages);
  console.log('  homepage card       ' + (home.patched ? 'updated' : (home.why || 'unchanged')));
  console.log('  sitemap             ' + (added ? added + ' added' : 'unchanged'));
  console.log('  sidebar             ' + nav.touched + ' page(s), ' + nav.skipped + ' skipped');
  console.log('\n  ' + changes.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

main();
