/**
 * Makes every tool installable as its own app.
 *
 *   node build-pwa.js          apply
 *   node build-pwa.js --check  report what would change, write nothing
 *
 * A browser will only install a page as a separate app if that page carries
 * its own manifest with its own id, scope and icons. One site-wide manifest
 * gives you one installable thing: "1234Tools". So this writes one manifest
 * per tool into /pwa/, points each page at it, and gives it the icon the page
 * already uses in its own heading.
 *
 * Icons are shared by glyph rather than by tool. The sprite has 158 glyphs for
 * 1,194 tools — every length converter is the same drawing — so generating one
 * icon per tool would mean a thousand identical files. build/make-pwa-icons.js
 * rasterises the set; this script only references it.
 *
 * The page edit is marker-delimited and idempotent, like build-site.js: run it
 * twice and the second run writes nothing.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const SITE = 'https://www.1234tools.com';

const START = '<!-- PWA: generated by build-pwa.js, do not edit -->';
const END = '<!-- /PWA -->';

const changes = [];
function write(rel, content) {
  const abs = path.join(ROOT, rel);
  const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (existing === content) return false;
  changes.push((existing === null ? 'create ' : 'update ') + rel);
  if (!CHECK) {
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, content);
  }
  return true;
}

/** The tool list the site already maintains for its own search box. */
function tools() {
  const src = fs.readFileSync(path.join(ROOT, 'assets/search-index.js'), 'utf8');
  const sandbox = { window: {} };
  new Function('window', src)(sandbox.window);
  return sandbox.window.SEARCH_INDEX.map(([title, url, id]) => ({ title, url, id }));
}

/**
 * The label under a home-screen icon.
 *
 * Launchers truncate this themselves, so the job is not to be short but to
 * keep whatever distinguishes this tool from its neighbours. Stripping the
 * trailing noun turned both QR tools into "QR Code", which is exactly the
 * failure to avoid: the two apps sit next to each other on the same screen.
 */
function shortName(title) {
  let s = title
    .replace(/^Convert\s+/i, '')
    .replace(/\s+to\s+/i, ' → ')
    .replace(/\s*[—–]\s*.*$/, '')
    .replace(/\s*\([^)]*\)\s*$/, '')
    .trim();
  if (!s) s = title;
  if (s.length <= 20) return s;
  const cut = s.slice(0, 20);
  const space = cut.lastIndexOf(' ');
  return (space > 7 ? cut.slice(0, space) : cut)
    .replace(/[\s,&+→-]+$/, '')          // no dangling "JSON Formatter &"
    .replace(/\s+(and|or|to|for|with|in|of)$/i, '')
    .trim();
}

const esc = (s) => String(s)
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&mdash;/g, '—');

/** Which section a tool sits in, for the manifest's categories field. */
const CATEGORY = {
  finance: ['finance'], business: ['business'], india: ['finance'],
  health: ['health', 'fitness'], mathematics: ['education'], engineering: ['education'],
  conversions: ['utilities', 'education'], developer: ['developer', 'productivity'],
  qr: ['utilities', 'productivity'], image: ['photo', 'utilities'],
  pdf: ['productivity', 'utilities'], text: ['productivity'], time: ['utilities'],
  utilities: ['utilities'], design: ['graphics']
};

function manifestFor(tool, meta) {
  const page = '/' + tool.url;
  return JSON.stringify({
    /* The id is what makes this a separate installation rather than another
       copy of the site. It must stay stable: change it and an installed app
       is orphaned. */
    id: page,
    name: meta.title + ' — 1234Tools',
    short_name: meta.short,
    description: meta.description,
    start_url: page + '?src=pwa',
    scope: page,
    display: 'standalone',
    display_override: ['standalone', 'minimal-ui'],
    orientation: 'any',
    theme_color: '#06080f',
    background_color: '#06080f',
    lang: 'en-GB',
    dir: 'ltr',
    categories: CATEGORY[tool.url.split('/')[0]] || ['utilities'],
    icons: [
      { src: '/assets/pwa/' + meta.glyph + '.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
      { src: '/assets/pwa/' + meta.glyph + '-maskable.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'maskable' },
      { src: '/assets/pwa/' + meta.glyph + '-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' }
    ]
  }, null, 2) + '\n';
}

/**
 * The search index gives every length conversion the same id, "length", so it
 * cannot name a manifest: 306 pages would share one file and install as one
 * app. The page path is the only thing that is unique per tool.
 */
function manifestPath(tool) {
  return 'pwa/' + tool.url.replace(/\.html$/, '') + '.webmanifest';
}

function pwaBlock(prefix, tool, meta) {
  return [
    START,
    '<link rel="manifest" href="' + prefix + manifestPath(tool) + '">',
    '<link rel="apple-touch-icon" href="' + prefix + 'assets/pwa/' + meta.glyph + '-192.png">',
    '<meta name="apple-mobile-web-app-capable" content="yes">',
    '<meta name="mobile-web-app-capable" content="yes">',
    '<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">',
    '<meta name="apple-mobile-web-app-title" content="' + meta.short.replace(/"/g, '&quot;') + '">',
    '<script src="' + prefix + 'assets/pwa.js" defer></script>',
    END
  ].join('\n');
}

/* Anything an earlier run, or the hand-built QR pages, may have left behind. */
const STALE = [
  /<link rel="manifest"[^>]*>\n?/g,
  /<link rel="apple-touch-icon"[^>]*>\n?/g,
  /<meta name="apple-mobile-web-app-capable"[^>]*>\n?/g,
  /<meta name="mobile-web-app-capable"[^>]*>\n?/g,
  /<meta name="apple-mobile-web-app-status-bar-style"[^>]*>\n?/g,
  /<meta name="apple-mobile-web-app-title"[^>]*>\n?/g,
  /<script src="[^"]*assets\/pwa\.js"[^>]*><\/script>\n?/g
];

function patch(tool, meta) {
  const abs = path.join(ROOT, tool.url);
  const before = fs.readFileSync(abs, 'utf8');
  const depth = tool.url.split('/').length - 1;
  const prefix = '../'.repeat(depth);

  let html = before;
  const old = html.indexOf(START);
  if (old >= 0) {
    const stop = html.indexOf(END, old);
    html = html.slice(0, old) + html.slice(stop + END.length + 1);
  }
  for (const re of STALE) html = html.replace(re, '');

  const anchor = '<link rel="stylesheet"';
  const at = html.indexOf(anchor);
  if (at < 0) return { skipped: true };
  html = html.slice(0, at) + pwaBlock(prefix, tool, meta) + '\n' + html.slice(at);

  if (html === before) return { changed: false };
  changes.push('update ' + tool.url);
  if (!CHECK) fs.writeFileSync(abs, html);
  return { changed: true };
}

/* ------------------------------------------------------------------ */

const list = tools();
const glyphs = new Set();
let patched = 0, skipped = [];

for (const tool of list) {
  const abs = path.join(ROOT, tool.url);
  if (!fs.existsSync(abs)) { skipped.push(tool.url + ' (no page)'); continue; }
  const html = fs.readFileSync(abs, 'utf8');

  const g = /<h1><svg class="ico ico-title"[^>]*><use href="[^#"]*#(i-[a-z0-9-]+)"/.exec(html);
  const d = /<meta name="description" content="([^"]*)"/.exec(html);
  if (!g || !d) { skipped.push(tool.url + ' (no glyph or description)'); continue; }

  const meta = {
    title: esc(tool.title),
    short: shortName(esc(tool.title)),
    description: esc(d[1]),
    glyph: g[1]
  };
  glyphs.add(meta.glyph);

  write(manifestPath(tool), manifestFor(tool, meta));
  if (patch(tool, meta).changed) patched++;
}

/* The icon set the manifests point at, for build/make-pwa-icons.js to draw. */
write('build/pwa-glyphs.json', JSON.stringify([...glyphs].sort(), null, 2) + '\n');

const missing = [...glyphs].filter(
  (gl) => !fs.existsSync(path.join(ROOT, 'assets/pwa', gl + '-192.png')));

console.log('build-pwa.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
console.log('');
console.log('  tools            ' + list.length);
console.log('  manifests        ' + changes.filter((c) => c.includes('.webmanifest')).length + ' written');
console.log('  pages patched    ' + patched);
console.log('  distinct glyphs  ' + glyphs.size);
if (missing.length) {
  console.log('  ! ' + missing.length + ' glyph(s) have no icon yet — run build/make-pwa-icons.js:');
  console.log('      ' + missing.slice(0, 6).join(', ') + (missing.length > 6 ? ', …' : ''));
}
if (skipped.length) {
  console.log('  ! skipped ' + skipped.length + ':');
  for (const s of skipped.slice(0, 8)) console.log('      ' + s);
}
console.log('');
console.log('  ' + changes.length + ' file(s) ' + (CHECK ? 'would change' : 'changed'));
