/**
 * Landing pages for the jobs people type into a search box, each with the
 * real tool on it, already set for that job.
 *
 *   node build-landing.js            apply
 *   node build-landing.js --check    report what would change, write nothing
 *   node build-landing.js --verbose  list the files
 *
 * "png to jpg", "compress image to 50kb", "passport photo 35x45",
 * "compress pdf to 200kb": each is one job a tool on this site already does,
 * but the tool's own page answers the general question, not that one. This
 * writes one page per job (build/landing/data.js holds the pages and their
 * words), at /<section>/<job>/:
 *
 *   - the tool itself, mounted from its own spec and engine files, opened
 *     with the job's preset through the tool's own link settings (the image
 *     shell's ?from=&to=, ?target=, ?preset=; the PDF shell's ?format=,
 *     ?kb=): a small script in the head adds the preset to the address
 *     before the tool reads it, unless the visitor's link already sets it;
 *   - the answer to the question in the page's own words, a real example
 *     whose figures were measured with that tool on that page (the test,
 *     build/tests/landing.js, runs each one again), the steps, questions and
 *     answers (also written into the JSON-LD), the tool's own privacy line,
 *     and links to the neighbouring pages and the full tool;
 *   - canonical, hreflang (English only, and x-default: there is no other
 *     language yet), Open Graph, a BreadcrumbList from build-crumbs.js.
 *
 * It refuses to write anything when a page's preset is one its tool would
 * not take (a key the tool has no control for, a value outside a select's
 * options or a number's range, a format the converter cannot name), when a
 * page would sit where another page already lives, when a sentence of eight
 * words or more appears on two landing pages or is copied from the tool's
 * own page, or when the copy says "100% private".
 *
 * Also written: a block on the /image/ and /pdf/ hubs listing the pages
 * (<!-- LANDING --> … <!-- /LANDING -->; plain links, not tool cards, so the
 * hubs' tool counts and job groups are untouched), and each page's line in
 * sitemap-1.xml. The pages are not tools and are not added to the search
 * index: build-finder.js reads finderRows() from here, and build-site.js
 * keeps them in the sitemap through paths().
 *
 * The shell of each page (head, header, sidebar, footer) is cut from the
 * tool's own page, so it is today's shell; the post-processors then treat
 * it like any other page. Run it after the generators that own the tools
 * and before build-finder.js. Requiring this file does nothing.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = __dirname;
const CHECK = process.argv.includes('--check');
const VERBOSE = process.argv.includes('--verbose');
const SITE = 'https://www.1234tools.com';
/* LANDING_DRAFT=1: build with unrecorded examples, so build/tests/landing.js --record can measure them; never for a release */
const DRAFT = process.env.LANDING_DRAFT === '1';

const HUB_OPEN = '<!-- LANDING: generated by build-landing.js, do not edit -->';
const HUB_CLOSE = '<!-- /LANDING -->';
const HUB_RE = /<!-- LANDING: generated by build-landing\.js, do not edit -->[\s\S]*?<!-- \/LANDING -->\n?/;
const PAGE_MARK = '<!-- LANDING-PAGE: written by build-landing.js from build/landing/data.js; edit there -->';
const DUP_WORDS = 8;
const BANNED = /100\s*%\s*(private|secure|safe)|completely private|totally private/i;
const US = /\b(color(s|ed|ing)?|center(s|ed)?|analyz\w*|optimiz\w*|favor(s|ite|ed)?|behavior\w*|organiz\w*|recogniz\w*|liters?|fiber|catalog)\b/i;

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const unesc = (s) => String(s).replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&amp;/g, '&');
const isStub = (html) => /name="robots" content="noindex/.test(html) && /http-equiv="refresh"/.test(html);
const D = () => require('./build/landing/data.js');

/* ------------------------------------------------------------------ */
/* the two tool shells, as far as a link can set them                  */
/* ------------------------------------------------------------------ */

const SHELLS = {
  IMAGE_TOOLS: {
    mount: 'mountImage', idPrefix: 'ic-', store: (id) => '1234tools-img-' + id + '-v1',
    /* engine/render-image.js: ALIASES and LONG_FORMAT */
    aliases: { q: 'quality', f: 'format', to: 'format' },
    formats: { webp: 'image/webp', jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', avif: 'image/avif', bmp: 'image/bmp', ico: 'image/x-icon', gif: 'image/gif', same: 'same' }
  },
  PDF_TOOLS: {
    mount: 'mountPDF', idPrefix: 'pc-', store: (id) => '1234tools-pdf-' + id + '-v1',
    aliases: {},
    /* engine/render-pdf.js: fromAddress()'s MIME short forms */
    formats: { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp' }
  }
};

/* ------------------------------------------------------------------ */
/* a tool, read from its own page and engine files                     */
/* ------------------------------------------------------------------ */

const toolCache = new Map();
function tool(href) {
  if (toolCache.has(href)) return toolCache.get(href);
  const rel = href.replace(/^\/+/, '') + 'index.html';
  const abs = path.join(ROOT, rel);
  if (!fs.existsSync(abs)) throw new Error('build-landing.js: the tool page ' + href + ' does not exist');
  const html = fs.readFileSync(abs, 'utf8');
  const m = /var spec = window\.(IMAGE_TOOLS|PDF_TOOLS)\['([^']+)'\];/.exec(html);
  if (!m) throw new Error('build-landing.js: ' + href + ' mounts neither an IMAGE_TOOLS nor a PDF_TOOLS spec');
  const registry = m[1], id = m[2];
  const head = html.slice(0, html.indexOf('</head>'));
  const scripts = [...head.matchAll(/<script src="\/engine\/([^"]+\.js)" defer><\/script>/g)].map((x) => x[1]);
  /* the spec, run in a vm against a stub window: only its own files and the
     data files it reads (no shell, no bundle, no vendor code) */
  const box = {
    console, URLSearchParams, Math, JSON, Number, String, Object, Array, Set, Map, Promise,
    location: { search: '', pathname: href, hash: '' }, navigator: { language: 'en-GB' },
    document: { addEventListener() {}, querySelector() { return null; }, querySelectorAll() { return []; }, createElement() { return { style: {}, getContext() { return null; } }; } }
  };
  box.window = box; box.self = box;
  const ctx = vm.createContext(box);
  for (const s of scripts) {
    if (/^(render-|zip\.js|vendor\/)|bundle/.test(s)) continue;
    const f = path.join(ROOT, 'engine', s);
    vm.runInContext(fs.readFileSync(f, 'utf8'), ctx, { filename: f });
  }
  const spec = box[registry] && box[registry][id];
  if (!spec) throw new Error('build-landing.js: ' + href + ': the engine files define no ' + registry + '["' + id + '"]');
  const glyph = (/<h1><svg class="ico ico-title"[^>]*><use href="[^#"]*#(i-[a-z0-9-]+)"/.exec(html) || [])[1];
  const privacy = (/<p class="privacy-line">([\s\S]*?)<\/p>/.exec(html) || [])[1];
  const title = (/<h1><svg[^>]*>[\s\S]*?<\/svg>([^<]+)<\/h1>/.exec(html) || [])[1];
  const mainText = unesc(html.slice(html.indexOf('<main'), html.indexOf('</main>')).replace(/<script[\s\S]*?<\/script>/g, ' ').replace(/<[^>]+>/g, ' '));
  const t = { href, rel, html, registry, id, spec, scripts, glyph, privacy, title: title ? unesc(title.trim()) : id, mainText, engineSrc: scripts.map((s) => fs.readFileSync(path.join(ROOT, 'engine', s), 'utf8')).join('\n') };
  if (!glyph || !privacy) throw new Error('build-landing.js: ' + href + ' has no title glyph or no privacy line to carry over');
  toolCache.set(href, t);
  return t;
}

/* ------------------------------------------------------------------ */
/* the preset: accepted by the tool, or the build stops                */
/* ------------------------------------------------------------------ */

/**
 * What the tool's controls must read once the page has opened with this
 * preset, as { '<control id>': value }, plus { drop: text } when the tool
 * names the expected file in its drop zone. Throws when the tool would not
 * take the preset.
 */
function expected(page, t) {
  const S = SHELLS[t.registry];
  const want = {};
  const consumed = new Set();
  const refuse = (why) => { throw new Error('build-landing.js: /' + page.section + '/' + page.slug + '/ asks ' + t.href + ' for ' + JSON.stringify(page.preset) + ', which it does not accept: ' + why); };
  const controls = t.spec.controls || [];
  for (const [k, v] of Object.entries(page.preset)) {
    const key = S.aliases[k] || k;
    if (controls.some((c) => c.key === key)) { want[key] = String(v); consumed.add(k); }
  }
  if (t.registry === 'PDF_TOOLS' && typeof t.spec.fromUrl === 'function') {
    const q = new URLSearchParams(page.preset);
    const before = JSON.stringify(want);
    t.spec.fromUrl(q, want);
    if (JSON.stringify(want) !== before) Object.keys(page.preset).forEach((k) => consumed.add(k));
  }
  const out = {};
  if ('from' in page.preset) {
    /* the converter's own setup: ?from= names the file it asks for (NAMES in its spec file) */
    const names = /const NAMES = \{([^}]*)\}/.exec(t.engineSrc);
    if (t.registry !== 'IMAGE_TOOLS' || t.id !== 'image-converter' || !names) refuse('only the Image Format Converter reads ?from=');
    const table = {};
    for (const m of names[1].matchAll(/(\w+):\s*'([^']+)'/g)) table[m[1]] = m[2];
    const from = String(page.preset.from).toLowerCase();
    if (!table[from]) refuse('?from=' + from + ' is not a format the converter names');
    const to = table[String(page.preset.to || '').toLowerCase()];
    out.drop = 'Choose ' + table[from] + ' images' + (to ? ' to convert to ' + to : '');
    consumed.add('from');
  }
  for (const k of Object.keys(page.preset)) if (!consumed.has(k)) refuse('it has no control or link setting called "' + k + '"');
  let changes = 0;
  for (const [key, raw] of Object.entries(want)) {
    const c = controls.find((x) => x.key === key);
    let v = raw;
    if (c.type === 'select') {
      const has = (x) => (c.options || []).some((o) => String(o.value) === x);
      const long = S.formats[String(v).toLowerCase()];
      if (!has(v) && long && has(long)) v = long;
      if (!has(v)) refuse('"' + key + '" has no option ' + raw);
    } else if (c.type === 'number' || c.type === 'range') {
      const n = Number(v);
      if (!isFinite(n) || (c.min !== undefined && n < c.min) || (c.max !== undefined && n > c.max)) refuse('"' + key + '" takes ' + c.min + ' to ' + c.max + ', not ' + raw);
      v = String(n);
    } else refuse('"' + key + '" is a ' + c.type + ' control, which a landing page does not set');
    if (String(v) !== String(c.default)) changes++;
    out[S.idPrefix + key] = String(v);
  }
  if (!changes && !out.drop && !page.presetIsDefault) refuse('every value is already the default, so the page would change nothing (mark presetIsDefault to say that is meant)');
  return out;
}

/* ------------------------------------------------------------------ */
/* the words                                                          */
/* ------------------------------------------------------------------ */

/** Example text with its {figures} filled in from the recorded run. */
function fill(text, shown, where) {
  return String(text).replace(/\{([a-zA-Z0-9]+)\}/g, (m, k) => {
    if ((!shown || shown[k] === undefined) && DRAFT) return '{' + k + '?}';
    if (!shown || shown[k] === undefined) throw new Error('build-landing.js: ' + where + ' quotes {' + k + '}, which its example did not record');
    return shown[k];
  });
}

function sentences(text) {
  return String(text).replace(/\s+/g, ' ').split(/(?<=[.!?:;])\s+/)
    .map((s) => s.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ').trim())
    .filter((s) => s.split(' ').length >= DUP_WORDS);
}

/** The page's own words, which must be its own: not on another landing page, not the tool page's. */
function ownWords(p) {
  const ex = p.example;
  return [].concat(p.lede, p.answer.paras, p.facts ? [] : [], p.faq.map((f) => f.a), ex ? fill(ex.text, ex.shown, p.slug) : []);
}

function checkWords(pages) {
  const seen = new Map();
  const problems = [];
  for (const p of pages) {
    const t = tool(p.tool);
    const all = ownWords(p).concat(p.steps, p.faq.map((f) => f.q), [p.title, p.description]);
    for (const s of all) {
      if (BANNED.test(s)) problems.push(p.slug + ': says "' + BANNED.exec(s)[0] + '"');
      const us = US.exec(s);
      if (us) problems.push(p.slug + ': American spelling "' + us[0] + '"');
    }
    const toolText = t.mainText.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ');
    for (const s of ownWords(p).flatMap(sentences)) {
      if (toolText.indexOf(s) >= 0) problems.push(p.slug + ': copies a sentence from ' + p.tool + ': "' + s + '"');
      const other = seen.get(s);
      if (other && other !== p.slug) problems.push(p.slug + ' and ' + other + ' share the sentence "' + s + '"');
      else seen.set(s, p.slug);
    }
    if (p.description.length > 160) problems.push(p.slug + ': description is ' + p.description.length + ' characters (160 at most)');
    if (p.faq.length < 3) problems.push(p.slug + ': ' + p.faq.length + ' questions (3 at least)');
    if (!DRAFT && (!p.example || !p.example.text || !p.example.shown || !Object.keys(p.example.shown).length)) problems.push(p.slug + ': no recorded example');
  }
  if (problems.length) throw new Error('build-landing.js: the words are not ready:\n  ' + problems.join('\n  '));
}

/* ------------------------------------------------------------------ */
/* a page                                                             */
/* ------------------------------------------------------------------ */

const urlOf = (p) => '/' + p.section + '/' + p.slug + '/';
const relOf = (p) => p.section + '/' + p.slug + '/index.html';

function presetScript(p) {
  return '<script>/* opens the tool below set for this page, through its own link settings, unless the link already sets them (build-landing.js) */\n' +
    '(function(){try{var q=new URLSearchParams(location.search),p=' + JSON.stringify(p.preset) + ',n=0;for(var k in p)if(!q.has(k)){q.set(k,p[k]);n++;}' +
    'if(n)history.replaceState(history.state,"",location.pathname+"?"+q.toString()+location.hash);}catch(e){}})();</script>\n';
}

function head(p, t, src) {
  const url = SITE + urlOf(p);
  let h = src.slice(0, src.indexOf('</head>'));
  const sub = (re, val) => {
    if (!re.test(h)) throw new Error('build-landing.js: ' + t.rel + ' has no ' + re);
    h = h.replace(re, () => val);
  };
  sub(/<title>[^<]*<\/title>/, '<title>' + esc(p.pageTitle) + '</title>');
  sub(/<meta name="description" content="[^"]*">/, '<meta name="description" content="' + esc(p.description) + '">');
  sub(/<link rel="canonical" href="[^"]*">/, '<link rel="canonical" href="' + url + '">\n' +
    '<link rel="alternate" hreflang="en" href="' + url + '">\n<link rel="alternate" hreflang="x-default" href="' + url + '">');
  h = h.replace(/<meta property="og:title" content="[^"]*">/, () => '<meta property="og:title" content="' + esc(p.pageTitle) + '">')
    .replace(/<meta property="og:description" content="[^"]*">/, () => '<meta property="og:description" content="' + esc(p.description) + '">')
    .replace(/<meta property="og:url" content="[^"]*">/, () => '<meta property="og:url" content="' + url + '">')
    .replace(/<meta property="og:image:alt" content="[^"]*">/, () => '<meta property="og:image:alt" content="' + esc(p.h1 + ' — free, runs in your browser. 1234Tools') + '">')
    .replace(/<meta name="twitter:title" content="[^"]*">/, () => '<meta name="twitter:title" content="' + esc(p.pageTitle) + '">')
    .replace(/<meta name="twitter:description" content="[^"]*">/, () => '<meta name="twitter:description" content="' + esc(p.description) + '">')
    .replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>\n?/, '')
    .replace(/<!-- PWA: generated by build-pwa\.js, do not edit -->[\s\S]*?<!-- \/PWA -->\n?/, '');
  /* the preset goes in before the engine files, which read the address */
  const at = h.indexOf('<script src="/engine/');
  if (at < 0) throw new Error('build-landing.js: ' + t.rel + ' loads no engine files');
  h = h.slice(0, at) + presetScript(p) + h.slice(at);
  return h;
}

function ld(p, trail, crumbs) {
  const url = SITE + urlOf(p);
  return '<script type="application/ld+json">' + JSON.stringify({
    '@context': 'https://schema.org',
    '@graph': [
      { '@type': 'SoftwareApplication', name: p.h1, description: p.description, url, applicationCategory: 'MultimediaApplication', operatingSystem: 'Any', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' } },
      crumbs.breadcrumbList(trail, p.h1, urlOf(p)),
      { '@type': 'FAQPage', '@id': url + '#faq', mainEntity: p.faq.map((f) => ({ '@type': 'Question', name: f.q, acceptedAnswer: { '@type': 'Answer', text: f.a } })) }
    ]
  }).replace(/<\//g, '<\\/') + '</script>\n';
}

/** The tool page's own mount script, pointed at the tool on this page. */
function mountScript(t) {
  const m = /<script>\ndocument\.addEventListener\('DOMContentLoaded',function\(\)\{\n  var spec = window\.(?:IMAGE_TOOLS|PDF_TOOLS)\[[\s\S]*?<\/script>/.exec(t.html);
  if (!m) throw new Error('build-landing.js: ' + t.rel + ' has no mount script to carry over');
  const parts = m[0].split("document.querySelector('.tool')");
  if (parts.length !== 2) throw new Error('build-landing.js: ' + t.rel + "'s mount script does not find its root as document.querySelector('.tool')");
  return parts.join("document.querySelector('.landing-tool')");
}

function siblings(p, all) {
  const same = all.filter((x) => x !== p && x.group === p.group);
  const pick = (p.related || []).map((slug) => all.find((x) => x.slug === slug)).filter(Boolean);
  const list = pick.concat(same.filter((x) => pick.indexOf(x) < 0)).slice(0, 6);
  return list;
}

function body(p, t, all, expect) {
  const ex = p.example;
  const S = SHELLS[t.registry];
  const presetNote = p.presetNote;
  const li = (x) => '<li>' + esc(x) + '</li>';
  const rel = siblings(p, all);
  return '<article class="landing" data-landing="' + esc(p.slug) + '" data-landing-tool="' + esc(t.id) + '" data-landing-store="' + esc(S.store(t.id)) + '" data-landing-expect="' + esc(JSON.stringify(expect)) + '">\n' +
    '  <p class="eyebrow">' + esc(p.eyebrow) + '</p>\n' +
    '  <h1><svg class="ico ico-title" aria-hidden="true" focusable="false"><use href="/assets/icons.svg#' + t.glyph + '"></use></svg>' + esc(p.h1) + '</h1>\n' +
    '  <p class="lede">' + esc(p.lede) + '</p>\n' +
    '  <div class="tool landing-tool" data-tool="' + esc(t.id) + '"><div class="tool-io"></div></div>\n' +
    '  <p class="landing-preset"><strong>Set for this page:</strong> ' + esc(presetNote) + ' Every other setting of the <a href="' + t.href + '">' + esc(t.title) + '</a> is here too.</p>\n' +
    '  <section class="panel landing-answer" aria-labelledby="la-h"><h2 id="la-h">' + esc(p.answer.h) + '</h2>' + p.answer.paras.map((x) => '<p>' + esc(x) + '</p>').join('') +
    (p.facts ? '<table class="landing-facts"><tbody>' + p.facts.map((f) => '<tr><th scope="row">' + esc(f[0]) + '</th><td>' + (f[2] ? '<a href="' + esc(f[2]) + '" rel="nofollow noopener" target="_blank">' + esc(f[1]) + '</a>' : esc(f[1])) + '</td></tr>').join('') + '</tbody></table>' : '') + '</section>\n' +
    '  <section class="panel landing-example example-result" aria-labelledby="lx-h"><h2 id="lx-h">A real example</h2><p>' + esc(fill(ex.text, ex.shown, p.slug)) + '</p>' +
    '<p class="landing-note">Measured with the tool on this page in Chrome on <time datetime="' + esc(ex.date) + '">' + esc(longDate(ex.date)) + '</time>' + (ex.source ? '; ' + esc(ex.source) : '') + '. Your own files will give their own figures.</p></section>\n' +
    '  <section class="panel"><h2>' + esc(p.stepsTitle) + '</h2><ol class="tips">' + p.steps.map(li).join('') + '</ol></section>\n' +
    '  <section class="panel"><h2>Privacy</h2><p class="privacy-line">' + t.privacy + '</p></section>\n' +
    '  <section class="panel" id="faq"><h2>Frequently asked questions</h2>' + p.faq.map((f) => '<details><summary>' + esc(f.q) + '</summary><p>' + esc(f.a) + '</p></details>').join('') + '</section>\n' +
    '  <section class="panel"><h2>Related</h2><ul class="related">' + rel.map((x) => '<li><a href="' + urlOf(x) + '">' + esc(x.h1) + '</a></li>').join('') + '<li><a href="' + t.href + '">' + esc(t.title) + '</a></li></ul></section>\n' +
    '</article>\n';
}

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
function longDate(iso) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(iso || '');
  if (!m) throw new Error('build-landing.js: example date ' + iso + ' is not YYYY-MM-DD');
  return Number(m[3]) + ' ' + MONTHS[Number(m[2]) - 1] + ' ' + m[1];
}

function page(p, all) {
  const crumbs = require('./build-crumbs.js');
  const sidebar = require('./build-sidebar.js');
  const outbound = require('./build-outbound.js');
  const hubs = require('./build-hubs.js');
  const { footerApply } = require('./build-site.js');
  const { trailFor } = require('./build/sections.js');
  const t = tool(p.tool);
  const expect = expected(p, t);
  const src = t.html;
  const open = '<main id="main" class="content">';
  const mainAt = src.indexOf(open), mainEnd = src.indexOf('</main>');
  if (mainAt < 0 || mainEnd < 0) throw new Error('build-landing.js: ' + t.rel + ' has no <main>');
  const trail = trailFor(urlOf(p));
  const html = head(p, t, src) + ld(p, trail, crumbs) + src.slice(src.indexOf('</head>'), mainAt + open.length) + '\n' +
    PAGE_MARK + '\n' + crumbs.render(trail, p.h1) + '\n' + body(p, t, all, expect) + mountScript(t) + '\n' + src.slice(mainEnd);
  const rel = relOf(p);
  /* as the post-processors would leave it, so a second run writes nothing */
  const share = require('./build-share.js');
  return { html: footerApply(share.apply(hubs.apply(outbound.rewrite(sidebar.apply(html, rel), p.section).html, rel), rel), rel), expect };
}

/* ------------------------------------------------------------------ */
/* the hubs, the finder, the sitemap                                   */
/* ------------------------------------------------------------------ */

function hubBlock(section, pages) {
  const mine = pages.filter((p) => p.section === section);
  const groups = [];
  for (const p of mine) { let g = groups.find((x) => x.name === p.group); if (!g) groups.push(g = { name: p.group, list: [] }); g.list.push(p); }
  return HUB_OPEN + '\n<section class="panel landing-hub" aria-labelledby="landing-hub-h"><h2 id="landing-hub-h">' + esc(D().HUBS[section].h) + '</h2><p>' + esc(D().HUBS[section].p) + '</p>' +
    groups.map((g) => '<h3>' + esc(g.name) + '</h3><ul class="landing-links">' + g.list.map((p) => '<li><a href="' + urlOf(p) + '">' + esc(p.h1) + '</a></li>').join('') + '</ul>').join('') +
    '</section>\n' + HUB_CLOSE + '\n';
}

function hubPage(src, section, pages) {
  const block = hubBlock(section, pages);
  if (HUB_RE.test(src)) return src.replace(HUB_RE, () => block);
  const anchor = D().HUBS[section].before;
  const at = anchor ? src.indexOf(anchor) : -1;
  const end = src.indexOf('</main>');
  const where = at >= 0 && at < end ? at : end;
  if (where < 0) throw new Error('build-landing.js: the /' + section + '/ hub has no </main>');
  return src.slice(0, where) + block + src.slice(where);
}

function patchSitemap(src, pages) {
  const add = pages.filter((p) => src.indexOf('<loc>' + SITE + urlOf(p) + '</loc>') < 0)
    .map((p) => '<url><loc>' + SITE + urlOf(p) + '</loc><changefreq>monthly</changefreq><priority>0.7</priority></url>');
  return add.length ? src.replace('</urlset>', add.join('\n') + '\n</urlset>') : src;
}

/** The pages, as data, after the build's checks. */
function pagesChecked() {
  const all = D().PAGES;
  const slugs = new Set();
  for (const p of all) {
    if (slugs.has(p.section + '/' + p.slug)) throw new Error('build-landing.js: ' + urlOf(p) + ' is in data.js twice');
    slugs.add(p.section + '/' + p.slug);
  }
  checkWords(all);
  return all;
}

/** For build-site.js: the landing pages, as site paths without the leading slash. */
function paths() {
  return D().PAGES.map((p) => p.section + '/' + p.slug + '/');
}

/** For build-finder.js: one row per landing page on disk, in its index's columns. */
function finderRows() {
  const { SECTIONS } = require('./build/sections.js');
  const rows = [];
  for (const p of D().PAGES) {
    if (!fs.existsSync(path.join(ROOT, relOf(p)))) continue;
    const t = tool(p.tool);
    rows.push([p.h1, p.section + '/' + p.slug + '/', t.glyph, SECTIONS['/' + p.section + '/'].name, p.description, (p.keywords || []).join(' | '), p.io]);
  }
  return rows;
}

/* ------------------------------------------------------------------ */

function main() {
  const all = pagesChecked();
  const changes = [];
  const write = (rel, content) => {
    const abs = path.join(ROOT, rel);
    const was = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
    if (was === content) return;
    changes.push((was === null ? 'create ' : 'update ') + rel);
    if (!CHECK) { fs.mkdirSync(path.dirname(abs), { recursive: true }); fs.writeFileSync(abs, content); }
  };
  for (const p of all) {
    const rel = relOf(p);
    const abs = path.join(ROOT, rel);
    if (fs.existsSync(abs) && fs.readFileSync(abs, 'utf8').indexOf(PAGE_MARK) < 0) throw new Error('build-landing.js: ' + urlOf(p) + ' is already another page; choose another address');
    if (fs.existsSync(path.join(ROOT, p.section, p.slug + '.html'))) throw new Error('build-landing.js: /' + p.section + '/' + p.slug + '.html exists (a redirect stub or an old page)');
    const built = page(p, all);
    /* keep what the post-processors added on a previous run */
    let html = built.html;
    if (fs.existsSync(abs)) html = keepGenerated(fs.readFileSync(abs, 'utf8'), html);
    write(rel, html);
  }
  for (const section of Object.keys(D().HUBS)) {
    const rel = section + '/index.html';
    write(rel, hubPage(fs.readFileSync(path.join(ROOT, rel), 'utf8'), section, all));
  }
  write('sitemap-1.xml', patchSitemap(fs.readFileSync(path.join(ROOT, 'sitemap-1.xml'), 'utf8'), all));
  let sw = false;
  if (changes.length) {
    const abs = path.join(ROOT, 'sw.js');
    const src = fs.readFileSync(abs, 'utf8');
    const next = src.replace(/var V = '1234tools-v(\d+)';/, (m, n) => "var V = '1234tools-v" + (Number(n) + 1) + "';");
    if (next !== src) { sw = true; if (!CHECK) fs.writeFileSync(abs, next); }
  }
  console.log('\nbuild-landing.js' + (CHECK ? '  (--check: nothing will be written)' : ''));
  const by = {};
  all.forEach((p) => { by[p.group] = (by[p.group] || 0) + 1; });
  console.log('  pages               ' + all.length + ' (' + Object.entries(by).map((e) => e[1] + ' ' + e[0].toLowerCase()).join(', ') + ')');
  console.log('  presets             ' + all.length + ' accepted by their tools');
  console.log('  hubs                ' + Object.keys(D().HUBS).map((s) => '/' + s + '/').join(', '));
  console.log('  service worker      ' + (sw ? (CHECK ? 'would bump' : 'bumped') : 'unchanged'));
  if (VERBOSE || CHECK) changes.forEach((c) => console.log('    ' + c));
  console.log('\n  ' + changes.length + ' file(s) ' + (CHECK ? 'would change' : 'changed') + '\n');
}

/* The generated blocks other scripts own (the sidebar counts, the header
   and footer totals, the version line) are written by those scripts; this
   one writes them as the tool page has them today, which is what they would
   write too. Nothing to carry over yet: kept as the one place to add it. */
function keepGenerated(was, now) { return now; }

if (require.main === module) {
  try { main(); } catch (e) { console.error(e.message); process.exit(1); }
}
module.exports = { paths, finderRows, expected, tool, pagesChecked, SHELLS, PAGE_MARK, HUB_OPEN, HUB_CLOSE };
